# $FreeBSD: 913481c856ef2bd4356613058d8ac0a8c919801f $

FILESDIR=	${LIBEXECDIR}/bsdconfig/include
FILES=		bsdconfig.hlp media.hlp messages.subr network_device.hlp \
		options.hlp tcp.hlp usage.hlp

.include <bsd.prog.mk>
