# $FreeBSD: c6f6124feeb30efa017ff24b2d6e38a9f9d1992e $

.PATH: ${SRCTOP}/sys/dev/xl

KMOD=	if_xl
SRCS=	bus_if.h device_if.h if_xl.c miibus_if.h miidevs.h pci_if.h xlphy.c opt_platform.h

.include <bsd.kmod.mk>
