# $FreeBSD: 367776c245a8a3e54fb0295d0ab3f95df0cb9db3 $

SUBDIR= include

FILESDIR=	${LIBEXECDIR}/bsdconfig/includes
FILES=		INDEX USAGE

SCRIPTSDIR=	${FILESDIR}
SCRIPTS=	includes.sh

.include <bsd.prog.mk>
