# $FreeBSD: 653ad229c7e6e78bb2246f6a1572a636af3c44b1 $

PACKAGE=	tests

TAP_TESTS_SH=	legacy_test

${PACKAGE}FILES+=		regress.00.out
${PACKAGE}FILES+=		regress.00a.in
${PACKAGE}FILES+=		regress.00b.in
${PACKAGE}FILES+=		regress.01.out
${PACKAGE}FILES+=		regress.01a.in
${PACKAGE}FILES+=		regress.01b.in
${PACKAGE}FILES+=		regress.02.out
${PACKAGE}FILES+=		regress.02a.in
${PACKAGE}FILES+=		regress.02b.in
${PACKAGE}FILES+=		regress.sh

.include <bsd.test.mk>
