# $FreeBSD: 65618e1f59dc86f2c07d60439fbefcb88462ce88 $

PACKAGE=	kerberos

PROG=	kf
MAN=	kf.1
CFLAGS+=	-I${KRB5DIR}/lib/asn1 \
		-I${KRB5DIR}/lib/roken
LIBADD=	krb5 roken vers

.include <bsd.prog.mk>

.PATH: ${KRB5DIR}/appl/kf
