// $FreeBSD: 47df397ce238085a55eace3a29e0ed258f1a11a5 $

#define LLVM_REVISION "llvmorg-11.0.1-0-g43ff75f2c3fe"
#define LLVM_REPOSITORY "git@github.com:llvm/llvm-project.git"

#define CLANG_REVISION "llvmorg-11.0.1-0-g43ff75f2c3fe"
#define CLANG_REPOSITORY "git@github.com:llvm/llvm-project.git"

// <Upstream revision at import>-<Local identifier in __FreeBSD_version style>
#define LLD_REVISION "llvmorg-11.0.1-0-g43ff75f2c3fe-1300007"
#define LLD_REPOSITORY "FreeBSD"

#define LLDB_REVISION "llvmorg-11.0.1-0-g43ff75f2c3fe"
#define LLDB_REPOSITORY "git@github.com:llvm/llvm-project.git"
