# ex:ts=8
#
# Makefile for amd
# 	This file is under a "BSD" copyright (c) by David O'Brien 1998
#
# $FreeBSD: 5382fd71b48c1a9e2f2bace92ffbdc769296c9fb $

.PATH:	${SRCTOP}/contrib/amd/wire-test

PROG=	wire-test
MAN=	wire-test.8

LIBADD=	amu

.include <bsd.prog.mk>
