# $FreeBSD: b5777315bbb65e63dfdf832feb97ec9ce679c87c $
PACKAGE=lib${LIB}
LIB=	pmcstat
INTERNALLIB=

SRCS=	\
	libpmcstat_event.c	\
	libpmcstat_image.c	\
	libpmcstat_logging.c	\
	libpmcstat_process.c	\
	libpmcstat_string.c	\
	libpmcstat_symbol.c

# If libpmcstat becomes public uncomment this line
#INCS=	libpmcstat.h

.include <bsd.lib.mk>
