# $FreeBSD: 5becabb5c957b9580ccc98b26fa786dff8fc9409 $
PACKAGE=lib${LIB}
LIB=	pmcstat
INTERNALLIB=

SRCS=	\
	libpmcstat_event.c	\
	libpmcstat_image.c	\
	libpmcstat_logging.c	\
	libpmcstat_process.c	\
	libpmcstat_string.c	\
	libpmcstat_symbol.c
INCS=	libpmcstat.h

.include <bsd.lib.mk>
