# $FreeBSD: releng/12.2/lib/libssp_nonshared/Makefile 356356 2020-01-04 20:19:25Z kevans $

PACKAGE=	clibs
LIB=		ssp_nonshared
NO_PIC=
MK_PROFILE=	no

SRCS=		libssp_nonshared.c
CFLAGS+=	-fPIC

.include <bsd.lib.mk>
