# $FreeBSD: dea48430b0db19b4aefdc14f4218e58f8db0311d $

.PATH: ${SRCTOP}/sys/dev/stge

KMOD=	if_stge
SRCS=	if_stge.c device_if.h bus_if.h pci_if.h
SRCS+=	miibus_if.h opt_platform.h

.include <bsd.kmod.mk>
