# $FreeBSD: 98b58adb41b644d52bf9e51246089ca9acf16b8d $

.PATH:	${SRCTOP}/sys/dev/drm
KMOD= 	sis
SRCS=	sis_drv.c sis_ds.c sis_mm.c
SRCS+=	device_if.h bus_if.h pci_if.h opt_drm.h

.include <bsd.kmod.mk>
