# $FreeBSD: 6a1eedda8a9f7ef78af85c3a3985a531ab95bcec $

SUBDIR= include share

FILESDIR=	${LIBEXECDIR}/bsdconfig/120.networking
FILES=		INDEX USAGE

SCRIPTSDIR=	${FILESDIR}
SCRIPTS=	defaultrouter devices hostname nameservers networking \
		wlanconfig

.include <bsd.prog.mk>
