#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: 830b23c8cf21f2e61b2dbc9f4726f4634a538dd2 $

PROG=	fstat
SRCS=	fstat.c fuser.c main.c
LINKS=	${BINDIR}/fstat ${BINDIR}/fuser
LIBADD=	procstat

MAN1=	fuser.1 fstat.1

.include <bsd.prog.mk>
