# $FreeBSD: 8aa23eb0daf2929d7e524d419f03d6f7c200b702 $

# I once used this extensively, but no longer have a modem.  Feel free
# to ask me questions about it, but I disclaim ownership now.  -Peter

PROG=	chat
MAN=	chat.8

.include <bsd.prog.mk>
