# $FreeBSD: d50237dbc9ec0a94e8fc6a23303655ce9bba555e $

PROG_CXX=	llvm-dwarfdump

SRCDIR=		llvm/tools/llvm-dwarfdump
SRCS+=		Statistics.cpp
SRCS+=		llvm-dwarfdump.cpp

LIBADD+=	z

.include "../llvm.prog.mk"
