# $FreeBSD: 6e91ad763ba1fb42060d76472613de99765b8239 $

PROG_CXX=	llvm-dwarfdump

SRCDIR=		llvm/tools/llvm-dwarfdump
SRCS+=		SectionSizes.cpp
SRCS+=		Statistics.cpp
SRCS+=		llvm-dwarfdump.cpp

LIBADD+=	z

.include "../llvm.prog.mk"
