# $FreeBSD: releng/12.2/usr.bin/clang/llvm-dwarfdump/Makefile 356462 2020-01-07 19:49:10Z dim $

PROG_CXX=	llvm-dwarfdump

SRCDIR=		llvm/tools/llvm-dwarfdump
SRCS+=		Statistics.cpp
SRCS+=		llvm-dwarfdump.cpp

LIBADD+=	z

.include "../llvm.prog.mk"
