# $FreeBSD: releng/12.2/usr.bin/clang/clang-format/Makefile 356462 2020-01-07 19:49:10Z dim $

PROG_CXX=	clang-format
MAN=

SRCDIR=		clang/tools/clang-format
SRCS+=		ClangFormat.cpp

.include "../clang.prog.mk"
