# $FreeBSD: 2ef5eabbe09df229763ea6043b88e3f84cd40869 $

.PATH: ${SRCTOP}/sys/dev/ata/chipsets

KMOD=	atahighpoint
SRCS=	ata-highpoint.c
SRCS+=	ata_if.h bus_if.h device_if.h pci_if.h

.include <bsd.kmod.mk>
