# $FreeBSD: b1544ba515d0c1d3aae98e131b90bfa6faf4d799 $
# $NetBSD: Makefile.inc,v 1.4 2008/10/25 22:27:36 apb Exp $

CODE=	ISO-8859
SED_EXP= 's/ISO-8859-x/ISO-8859-%%PART%%/'

.include "../Makefile.part"
