#       $NetBSD: Makefile,v 1.3 2009/04/14 22:15:26 lukem Exp $
# $FreeBSD: d12ea095fb95fcbf025c205fe03bdb6dc0934307 $

.include <src.opts.mk>

PROG=	seq

LIBADD=	m

HAS_TESTS=
SUBDIR.${MK_TESTS}+=	tests

.include <bsd.prog.mk>
