# $FreeBSD: c01c2fdedbbfa4eec3eafae6beb6afeca45c3a9d $

PROG=	nandtool
SRCS=	nandtool.c nand_read.c nand_write.c nand_erase.c nand_info.c
SRCS+=	nand_readoob.c nand_writeoob.c
BINDIR=	/usr/sbin
LIBADD=	geom
MAN=	nandtool.8

.include <bsd.prog.mk>
