# $FreeBSD: 0522432e666be177a06537861f96102f7a7bccc6 $

PACKAGE=	tests

TESTSDIR=	${TESTSBASE}/usr.bin/bmake/sysmk/t0/2/1

TAP_TESTS_SH=	legacy_test

${PACKAGE}FILES+=		Makefile.test
${PACKAGE}FILES+=		expected.status.1
${PACKAGE}FILES+=		expected.stderr.1
${PACKAGE}FILES+=		expected.stdout.1

.include <bsd.test.mk>
