# $FreeBSD: releng/12.2/lib/libclang_rt/safestack/Makefile 360545 2020-05-01 20:20:23Z dim $

.include <bsd.init.mk>

LIB=		clang_rt.safestack-${CRTARCH}

SRCS+=		interception/interception_linux.cpp
SRCS+=		interception/interception_type_test.cpp
SRCS+=		safestack/safestack.cpp

.include <bsd.lib.mk>
