#	From: @(#)Makefile	6.3 (Berkeley) 6/8/93
# $FreeBSD: 7f7670c455337242f53ed7aa4d43e179677ce9f2 $

VOLUME=		papers
DOC=		diskperf
SRCS=		abs.ms motivation.ms equip.ms methodology.ms tests.ms \
		results.ms conclusions.ms appendix.ms
MACROS=		-ms
USE_TBL=

.include <bsd.doc.mk>
