#	@(#)Makefile	5.4 (Berkeley) 6/5/91
# $FreeBSD: 6ef9f5f8a2a0488471c9e83f2ca2c504253b38b2 $

PACKAGE=runtime
PROG=	etherswitchcfg
MAN=	etherswitchcfg.8
SRCS=	etherswitchcfg.c ifmedia.c
CFLAGS+= -I${SRCTOP}/sys

.include <bsd.prog.mk>
