# $FreeBSD: 655e67bebb5eb7b9da4f7ad77bf42f8c6e94ce9c $

.PATH: ${SRCTOP}/sys/netinet/libalias

KMOD=	libalias
SRCS=	alias.c alias_db.c alias_proxy.c alias_util.c alias_mod.c alias_sctp.c

.include <bsd.kmod.mk>
