# $FreeBSD: 5d5e8b560bbf8fe4bd21fad1a066d9ff43982eb3 $

.PATH: ${SRCTOP}/lib/libc/iconv

PROG=	mkcsmapper
LDFLAGS+= -L${SRCTOP}/lib/libc

NO_WMISSING_VARIABLE_DECLARATIONS=

.include "${.CURDIR}/Makefile.inc"
.include <bsd.prog.mk>
