# $FreeBSD: e7f8065fa1af1a6b2a0d2c22f5bb0e1bda391442 $

S=     ${SRCTOP}/sys

.PATH: $S/dev/usb/input

KMOD=	wmt
SRCS=	opt_bus.h opt_usb.h device_if.h bus_if.h usb_if.h usbdevs.h wmt.c

.include <bsd.kmod.mk>
