# $FreeBSD: 32899e9e7a34768f7ee8391928d4da301e16d57b $

.PATH: ${SRCTOP}/sys/security/mac_bsdextended

KMOD=	mac_bsdextended
SRCS=	vnode_if.h \
	mac_bsdextended.h \
	mac_bsdextended.c \
	ugidfw_system.c \
	ugidfw_vnode.c

.include <bsd.kmod.mk>
