# $FreeBSD: dea788d288b36608c421e0d15fa47cc9ce4aeacd $

PACKAGE=	tests

TESTSDIR=	${TESTSBASE}/usr.bin/bmake/sysmk/t1/mk

${PACKAGE}FILES+=		sys.mk.test

${PACKAGE}FILESNAME_sys.mk.test=	sys.mk

.include <bsd.test.mk>
