# $FreeBSD: 0c080c0861b35755cbf9eca2e361fec863ff0819 $

PACKAGE=utilities
FILESDIR= ${SHAREDIR}/examples/smbfs/print
FILES=	lj6l ljspool printcap.sample tolj

.PATH: ${SRCTOP}/contrib/smbfs/examples/print

.include <bsd.prog.mk>
