# $Id: Makefile,v 1.5 2003/08/14 20:06:21 max Exp $
# $FreeBSD: 8a0d422ee74ae65f93438e1b196a3df5ad6b43f2 $

PACKAGE=	bluetooth
PROG=		hcseriald
MAN=		hcseriald.8
WARNS?=		2

LIBADD=		netgraph

.include <bsd.prog.mk>
