# $FreeBSD: b7a989656907ed463d8337cfe85a3532b7e20b87 $

PROG_CXX=	llvm-diff

SRCDIR=		llvm/tools/llvm-diff
SRCS+=		DiffConsumer.cpp
SRCS+=		DiffLog.cpp
SRCS+=		DifferenceEngine.cpp
SRCS+=		llvm-diff.cpp

.include "../llvm.prog.mk"
