# $FreeBSD: releng/12.2/usr.bin/clang/llvm-diff/Makefile 356462 2020-01-07 19:49:10Z dim $

PROG_CXX=	llvm-diff

SRCDIR=		llvm/tools/llvm-diff
SRCS+=		DiffConsumer.cpp
SRCS+=		DiffLog.cpp
SRCS+=		DifferenceEngine.cpp
SRCS+=		llvm-diff.cpp

.include "../llvm.prog.mk"
