# $FreeBSD: 6031f8b2a12dc648aee27f8b96cf5dbe9e4cca51 $

PROG_CXX=	llvm-diff

SRCDIR=		llvm/tools/llvm-diff
SRCS+=		lib/DiffConsumer.cpp
SRCS+=		lib/DiffLog.cpp
SRCS+=		lib/DifferenceEngine.cpp
SRCS+=		llvm-diff.cpp

.include "../llvm.prog.mk"
