# $Id: Makefile,v 1.2 2003/04/27 00:22:11 max Exp $
# $FreeBSD: 9169cf113491c988c802448e6523d01e54ca9154 $

SUBDIR=	\
	bluetooth \
	hci	\
	l2cap	\
	socket	\
	bt3c	\
	ubt	\
	ubtbcmfw

.include <bsd.subdir.mk>
