# $Id: Makefile,v 1.2 2003/04/27 00:22:11 max Exp $
# $FreeBSD: 4d353fd94f4b68099ed42770c3c2e84ff1b44e9d $

SUBDIR=	\
	bluetooth \
	hci	\
	l2cap	\
	socket	\
	ubt	\
	ubtbcmfw

.include <bsd.subdir.mk>
