# $FreeBSD: 4539ba6cf8c42f9baf9ef1cc64390ce86345d943 $

NEED_COMPAT=	32
.include <bsd.compat.mk>

PROG=	ld-elf32.so.1
MAN=
MLINKS=	rtld.1 ld-elf32.so.1

.PATH:  ${SRCTOP}/libexec/rtld-elf
.include "${SRCTOP}/libexec/rtld-elf/Makefile"
