# $FreeBSD: 18fc45c24e2070b814524d0383279dfd7689eaf1 $

SUBDIR=	src .WAIT \
	wpa_supplicant \
	wpa_cli \
	wpa_passphrase \
	hostapd \
	hostapd_cli \
	ndis_events

SUBDIR_PARALLEL=

.include <bsd.subdir.mk>
