# $FreeBSD: 21ecbec033601904addfa4c876e7db2d4253a11a $

PACKAGE=	tests

TESTSDIR=	${TESTSBASE}/sys/geom/class/${.CURDIR:T}

# TODO: port the perl tests in tools/regression/geom_gpt
ATF_TESTS_SH+=	misc

.include <bsd.test.mk>
