# $FreeBSD: 63f365d0445ab6f423c26620463026d3d904ab12 $

ZFSTOP=	${SRCTOP}/sys/contrib/openzfs

.PATH: ${ZFSTOP}/cmd/zstreamdump
.PATH: ${ZFSTOP}/man/man8

SCRIPTS=	zstreamdump
MAN=	zstreamdump.8

.include <bsd.prog.mk>
