# $FreeBSD: dd75be1ca02aa5c0f8819cab6550480f7d187706 $

PACKAGE=	tests

ATF_TESTS_SH=	diff3_test

${PACKAGE}FILES+=	\
	1.txt \
	2.txt \
	3.txt \
	1.out \
	2.out \
	3.out \
	4.out \
	5.out \
	6.out \
	7.out \
	8.out \
	9.out

.include <bsd.test.mk>
