#	$FreeBSD: d9b2ed5ef6e394b548d4c2291e52e0d1cd72bf97 $

PACKAGE=	ipf
PROG=		ipresend
SRCS=		ipresend.c ip.c resend.c sbpf.c sock.c 44arp.c
MAN=		ipresend.1

.PATH:		${SRCTOP}/contrib/ipfilter/ipsend

.include <bsd.prog.mk>
