#	$FreeBSD: a4403d53754784044f089adf9ccb250a452c7d26 $

PACKAGE=	ipf
PROG=		ipresend
SRCS=		ipresend.c ip.c resend.c sbpf.c sock.c 44arp.c
MAN=		ipresend.1

.PATH:		${.CURDIR:H}/ipsend

.include <bsd.prog.mk>
