# $FreeBSD: af83cee4715886514a33b12343a01fe3010222ae $

SUBDIR= include

FILESDIR=	${LIBEXECDIR}/bsdconfig/130.security
FILES=		INDEX USAGE

SCRIPTSDIR=	${FILESDIR}
SCRIPTS=	kern_securelevel security

.include <bsd.prog.mk>
