# $FreeBSD: 4a46f612a0b6d646e17a2b728b42b1f22543d957 $

.PATH:	${SRCTOP}/sys/dev/gpio
KMOD=	bytgpio
SRCS=	bytgpio.c
SRCS+=	acpi_if.h device_if.h bus_if.h gpio_if.h opt_acpi.h opt_platform.h

.include <bsd.kmod.mk>
