# $Id: Makefile,v 1.6 2003/08/14 20:06:24 max Exp $
# $FreeBSD: 9e3e0bd50a479d86d592b27899e8f95839e70dbe $

PACKAGE=	bluetooth
PROG=		l2ping
MAN=		l2ping.8
WARNS?=		2

LIBADD=		bluetooth

.include <bsd.prog.mk>
