# $FreeBSD: 50a8ff7bd59f574ed4aabb2986f2d170c08e413f $

PACKAGE=	tests

TESTSDIR=	${TESTSBASE}/usr.bin/bmake/variables/t0

TAP_TESTS_SH=	legacy_test

${PACKAGE}FILES+=	Makefile.test
${PACKAGE}FILES+=	expected.status.1
${PACKAGE}FILES+=	expected.stderr.1
${PACKAGE}FILES+=	expected.stdout.1

.include <bsd.test.mk>
