# $FreeBSD: 8fcb2e1e5c648651a164dbb073c13bb1f9d085c2 $

.include <src.opts.mk>

SUBDIR=		cap_dns
SUBDIR+=	cap_fileargs
SUBDIR+=	cap_grp
SUBDIR+=	cap_net
SUBDIR+=	cap_pwd
SUBDIR+=	cap_sysctl
SUBDIR+=	cap_syslog

SUBDIR.${MK_TESTS}+=	tests

SUBDIR_PARALLEL=

.include <bsd.subdir.mk>
