# $FreeBSD: c735063d4050c588513e03f08b7eb038ba22e9b9 $

.include <src.opts.mk>

SUBDIR=		cap_dns
SUBDIR+=	cap_grp
SUBDIR+=	cap_pwd
SUBDIR+=	cap_random
SUBDIR+=	cap_sysctl
SUBDIR+=	cap_syslog

SUBDIR.${MK_TESTS}+=	tests

SUBDIR_PARALLEL=

.include <bsd.subdir.mk>
