# $FreeBSD: e36be05e7b71d5f69cacaf4289f14ce109e1c3d0 $

.PATH: ${SRCTOP}/cddl/contrib/opensolaris/cmd/zlook

PROG=	zlook
MAN=

WARNS?=	0
CFLAGS+= -I${SRCTOP}/sys/cddl/compat/opensolaris
CFLAGS+= -I${SRCTOP}/sys/cddl/contrib/opensolaris/uts/common

.include <bsd.prog.mk>
