# $FreeBSD: 36cdb31270888211ca53bdbac306c3ab06b2e1e3 $

.PATH:		${SRCTOP}/sys/dev/iicbus
KMOD		= iichid
SRCS		= iichid.c
SRCS		+= acpi_if.h bus_if.h device_if.h hid_if.h iicbus_if.h opt_hid.h

.include <bsd.kmod.mk>
