#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: ec3dc1ab7e156dd08aab332201dd8f442dd2927f $

PROG=	quotaon
LINKS=	${BINDIR}/quotaon ${BINDIR}/quotaoff
MAN=	quotaon.8
MLINKS=	quotaon.8 quotaoff.8

LIBADD=	util

.include <bsd.prog.mk>
