# $FreeBSD: 29862adcd1e26b7126a21009689c4759a4b811db $

LSDIR=	${SRCTOP}/contrib/less
.PATH:	${LSDIR}

CFLAGS+=-I${SRCTOP}/usr.bin/less -I${LSDIR}
WARNS?=	1

.SUFFIXES: .nro .1

.nro.1:
	cat ${.IMPSRC} > ${.TARGET}
