# $FreeBSD: c216656637b48b6fc91b9fa7fcf73d7082312327 $

SUBDIR += ataacard ataacerlabs ataamd ataati atacenatek atacypress atacyrix atahighpoint ataintel ataite atajmicron atamarvell atamicron atanational atanetcell atanvidia atapromise ataserverworks atasiliconimage atasis atavia

.include <bsd.subdir.mk>
