# $FreeBSD: 284a370c0167afe212269af68edb78ea08ff317f $

.include <src.opts.mk>

SUBDIR=	lib .WAIT \
	sbin share usr.bin usr.libexec usr.sbin

SUBDIR.${MK_TESTS}+= tests

SUBDIR_PARALLEL=

.include <bsd.subdir.mk>
