# $FreeBSD: 5ccd78f6d99dbc9fed328db8c92492a186a617e5 $

FILESGROUPS=	CONF LICENSE
CONF=		exclude-from-upgrade pc-sysinstall.conf avail-langs
CONFDIR=	${SHAREDIR}/pc-sysinstall/conf
LICENSE=	licenses/bsd-en.txt licenses/intel-en.txt licenses/nvidia-en.txt
LICENSEDIR=	${SHAREDIR}/pc-sysinstall/conf/license

.include <bsd.prog.mk>
