# $FreeBSD: f7cab6c3bae60f1b6be2e9e1d1a25d81996a1d17 $

PACKAGE=	tests

TESTSDIR=	${TESTSBASE}/usr.bin/bmake/shell/meta

TAP_TESTS_SH=	legacy_test

${PACKAGE}FILES+=	Makefile.test
${PACKAGE}FILES+=	expected.status.1
${PACKAGE}FILES+=	expected.status.2
${PACKAGE}FILES+=	expected.stderr.1
${PACKAGE}FILES+=	expected.stderr.2
${PACKAGE}FILES+=	expected.stdout.1
${PACKAGE}FILES+=	expected.stdout.2
${PACKAGE}FILES+=	sh

.include <bsd.test.mk>
