# $FreeBSD: releng/12.2/lib/libveriexec/Makefile 359913 2020-04-14 01:07:58Z sjg $

.include <src.opts.mk>

LIB=		veriexec
MAN=		veriexec.3
INCS=		libveriexec.h

WARNS?=		2

SRCS=		veriexec_check.c

.include <bsd.lib.mk>

