# $FreeBSD: 62a9e7141efc3609f78a8a3fcef39054f51a6dc2 $

SUBDIR= include share

FILESDIR=	${LIBEXECDIR}/bsdconfig/140.startup
FILES=		INDEX USAGE

SCRIPTSDIR=	${FILESDIR}
SCRIPTS=	misc rcadd rcconf rcdelete rcedit rcvar startup

.include <bsd.prog.mk>
