# $FreeBSD: 7bc1ac89c2966d4f1417027bd6a6db644026c6e3 $

.include <src.opts.mk>

PROG=	units
FILES=	definitions.units
FILESDIR=	${SHAREDIR}/misc

LIBADD=	edit

HAS_TESTS=
SUBDIR.${MK_TESTS}+= tests

.include <bsd.prog.mk>
