# $FreeBSD: 41aeee08895b04ee0b426c8209f2d30cc6e72f9f $

PACKAGE=	tests

ATF_TESTS_SH+=	unified_patch_test

${PACKAGE}FILES+=		PR74127-cline.diff
${PACKAGE}FILES+=		PR74127-good.diff
${PACKAGE}FILES+=		PR74127-repro.diff
${PACKAGE}FILES+=		PR74127.in

.include <bsd.test.mk>
