# $FreeBSD: e9c50308b3fabd2ebd1af51ba3c9a0f614f7cc08 $

SUBDIR=	hxtool kadmin kcc kdestroy kgetcred kf kinit kpasswd krb5-config ksu \
	string2key verify_krb5_conf
SUBDIR_PARALLEL=

.include <bsd.subdir.mk>
