#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: b9256f3cec30af825dad968fd67476670633cc62 $

.include <src.opts.mk>

PROG=	du
LIBADD=	util

HAS_TESTS=
SUBDIR.${MK_TESTS}+=	tests

.include <bsd.prog.mk>
