#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: 2f16201d171d19aaeb24677dc8198bea730365c5 $

.include <src.opts.mk>

PACKAGE=	runtime
PROG=	du
LIBADD=	util

HAS_TESTS=
SUBDIR.${MK_TESTS}+=	tests

.include <bsd.prog.mk>
