# $FreeBSD: 978b1e1e068b06ef9586f79b3fa3c00ad1797d39 $

.PATH: ${.CURDIR}/../man4.arm # Some manpages are common to arm and aarch64

MAN=	\
	armv8crypto.4 \
	aw_gpio.4 \
	aw_mmc.4 \
	aw_rtc.4 \
	aw_sid.4 \
	aw_spi.4 \
	aw_syscon.4 \
	bcm283x_pwm.4 \
	rk_gpio.4 \
	rk_grf.4 \
	rk_i2c.4 \
	rk_pinctrl.4 \

MANSUBDIR=/aarch64

.include <bsd.prog.mk>
