# $FreeBSD: 4677e7c7e6c7cd83ce66c62bf35f721965fa76b5 $

PROG=	lesskey
SRCS=	lesskey.c lesskey_parse.c version.c xbuf.c
CLEANFILES= lesskey.1

.include "${SRCTOP}/usr.bin/less/Makefile.common"
.include <bsd.prog.mk>
