# $FreeBSD: cf82f5d1b3a1feca0420370a1ba8b6163c147708 $

.PATH: ${.PARSEDIR:H:H}/dev/veriexec

.include <bsd.own.mk>

KMOD=	veriexec
SRCS=	verified_exec.c
SRCS+=	bus_if.h device_if.h vnode_if.h

.include <bsd.kmod.mk>

