# $FreeBSD: 5939a78c4e116607f3da2cf59a050b8585b7c878 $

.PATH: ${SRCTOP}/sys/cddl/contrib/opensolaris/common/avl

LIB=	avl
SRCS=	avl.c
WARNS?=	3
CFLAGS+= -I${SRCTOP}/sys/cddl/compat/opensolaris
CFLAGS+= -I${SRCTOP}/sys/cddl/contrib/opensolaris/uts/common

.include <bsd.lib.mk>
