# $FreeBSD: f9ee77d37883e4506a5abbe660143bdcfa47c0b9 $

.include <bsd.own.mk>

MOD=    lm75
SRCS=   snmp_lm75.c
XSYM=   begemotLm75
MAN=    snmp_lm75.3

BMIBS=  BEGEMOT-LM75-MIB.txt
DEFS=   ${MOD}_tree.def

.include <bsd.snmpmod.mk>
