# $FreeBSD: releng/12.2/sys/modules/tcp/tcpmd5/Makefile 365270 2020-09-02 19:02:48Z jhb $

.PATH: ${SRCTOP}/sys/netipsec

KMOD=   tcpmd5
SRCS=   xform_tcp.c opt_inet.h opt_inet6.h opt_ipsec.h

.include <bsd.kmod.mk>
