#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: 7af4395be78fdd596a0e4ca0b63ac0888be5b4d6 $

.include <src.opts.mk>

PROG=	apply

LIBADD=	sbuf

HAS_TESTS=
SUBDIR.${MK_TESTS}+= tests

.include <bsd.prog.mk>
