# $FreeBSD: 1d1fbf375a0ee1a5ad5c170e087daf5e5c560c9d $

.PATH:		${SRCTOP}/contrib/hyperv/tools/scripts

BINDIR=		${LIBEXECDIR}/hyperv

PACKAGE=	hyperv-tools
SCRIPTS=	hv_set_ifconfig hv_get_dns_info hv_get_dhcp_info
SCRIPTS+=	hyperv_vfattach hyperv_vfup

.include <bsd.prog.mk>
