# $FreeBSD: 6e251b24faa7affc1c99cf25d30548d5128371ac $

.PATH:		${SRCTOP}/contrib/hyperv/tools/scripts

BINDIR=		${LIBEXECDIR}/hyperv

SCRIPTS=	hv_set_ifconfig hv_get_dns_info hv_get_dhcp_info
SCRIPTS+=	hyperv_vfattach hyperv_vfup

.include <bsd.prog.mk>
