# $FreeBSD: 4fd44374ce54cdaf925592765e012e49633b2ff8 $

.PATH: ${SRCTOP}/sys/dev/ata/chipsets

KMOD=	atanvidia
SRCS=	ata-nvidia.c
SRCS+=	ata_if.h bus_if.h device_if.h pci_if.h

.include <bsd.kmod.mk>
