# $FreeBSD: 4aa8ec1c4f9f1b5e4a3b98dc9deaf871830a4372 $

.PATH: ${SRCTOP}/sys/geom/part

KMOD=	geom_part_ebr
SRCS=	g_part_ebr.c

SRCS+=	bus_if.h device_if.h g_part_if.h
SRCS+=	opt_geom.h

.include <bsd.kmod.mk>
