# $FreeBSD: a6fe85fe8252f4e76ae0e5de5a5023ff3e07585b $

.PATH: ${SRCTOP}/sys/dev/fxp

KMOD=	if_fxp
SRCS=	device_if.h bus_if.h if_fxp.c inphy.c miibus_if.h miidevs.h pci_if.h opt_platform.h

.include <bsd.kmod.mk>
