# $FreeBSD: aca711070fc5522cf517b1b0a5b415f8aff48bef $

.PATH: ${SRCTOP}/sys/powerpc/powernv

KMOD=	opal_nvram
SRCS=	opal_nvram.c
SRCS+=	bus_if.h device_if.h
SRCS+=	ofw_bus_if.h

.include <bsd.kmod.mk>
