#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: e3b05330828294543a1201e3e7dbe959177ef4bd $

PROG=	pstat
LINKS=	${BINDIR}/pstat ${BINDIR}/swapinfo
MAN=	pstat.8
MLINKS=	pstat.8 swapinfo.8

LIBADD=	kvm util

.include <bsd.prog.mk>
