# $FreeBSD: 127c874fbaf6f63121f232ab4e4d028bf30a0a79 $

SUBDIR= include share

FILESDIR=	${LIBEXECDIR}/bsdconfig/070.usermgmt
FILES=		INDEX USAGE

SCRIPTSDIR=	${FILESDIR}
SCRIPTS=	groupadd groupdel groupedit useradd userdel useredit usermgmt

.include <bsd.prog.mk>
