# $FreeBSD: 8ca0f0c8a76fdd283c3fd3b123ce99fccd97adc9 $

OPENPAM=	${SRCTOP}/contrib/openpam
.PATH: ${OPENPAM}/include ${OPENPAM}/bin/pamtest

PROG= pamtest
SRCS= pamtest.c

LIBADD=	pam

.include <bsd.prog.mk>
