#
# This builds a variety of text processing tools that
# may be useful on an embedded device.
#
# $FreeBSD: a913d46059750e528bf132784ba54fb7f6e66cbb $
#

# Sed
CRUNCH_PROGS_usr.bin+=	sed

# Awk
# Disable - it's big! -adrian
#CRUNCH_PROGS_usr.bin+=	awk
#CRUNCH_BUILDTOOLS+=	usr.bin/awk

# vi
# Disable - it's big! -adrian
#CRUNCH_PROGS_usr.bin+=	vi

CRUNCH_PROGS_usr.bin+=	ee
