#
# Build hostap/wpa_supplicant and supporting utilities.
#
# $FreeBSD: 631643188bf1f840b7b9a0b660fd63465bb13de4 $
#
.include <src.opts.mk>
CRUNCH_PROGS_usr.sbin+=	hostapd hostapd_cli
CRUNCH_SRCDIR_hostapd=	$(.CURDIR)/../../usr.sbin/wpa/hostapd
CRUNCH_SRCDIR_hostapd_cli=	$(.CURDIR)/../../usr.sbin/wpa/hostapd_cli

#CRUNCH_PROGS_usr.sbin+=	wpa_supplicant wpa_cli
#CRUNCH_SRCDIR_wpa_supplicant=	$(.CURDIR)/../../usr.sbin/wpa/wpa_supplicant
#CRUNCH_SRCDIR_wpa_cli=	$(.CURDIR)/../../usr.sbin/wpa/wpa_cli

.if ${MK_OFED} != "no"
# libpcap dependencies if OFED is enabled
CRUNCH_LIBS+=	-lmlx5 -libverbs
.endif
CRUNCH_LIBS+=	-lpcap

