# $FreeBSD: 16a89009bb6e0b0f026547c5ded4af3459d7c8a0 $

SUBDIR= include

FILESDIR=	${LIBEXECDIR}/bsdconfig/050.diskmgmt
FILES=		INDEX USAGE

SCRIPTSDIR=	${FILESDIR}
SCRIPTS=	diskmgmt

.include <bsd.prog.mk>
