# $FreeBSD: 7a20215305d27f200ddcf79a91d3639cb85aa682 $

SUBDIR=	intel_ipw \
	intel_iwi \
	intel_iwlwififw \
	intel_iwn \
	intel_wpi \
	realtek

SUBDIR_PARALLEL=

.include <bsd.arch.inc.mk>
.include <bsd.subdir.mk>
