#! /bin/sh
# $FreeBSD: 697ec0b5be850ec3005fa2dd885fcf02d9392847 $

L=/home/ctm/log.dequeue
/usr/sbin/ctm_dequeue -n 1 -l $L /home/ctm/queue/ctm-cvs-cur
/usr/sbin/ctm_dequeue -n 1 -l $L /home/ctm/queue/ctm-src-cur
