# $FreeBSD: f13524c91251649c01372cffcae037bd09855f86 $

.PATH: ${SRCTOP}/sys/dev/msk

KMOD=	if_msk
SRCS=	if_msk.c device_if.h bus_if.h pci_if.h
SRCS+=	miibus_if.h opt_platform.h

.include <bsd.kmod.mk>
