# $FreeBSD: a7a1ec8fc9ed5bdea354df5b5e4733a062fa8ec9 $

.PATH: ${SRCTOP}/sys/dev/ata/chipsets

KMOD=	atanational
SRCS=	ata-national.c
SRCS+=	ata_if.h bus_if.h device_if.h pci_if.h

.include <bsd.kmod.mk>
