# $FreeBSD: 7370b7ac90b7964ea04e960d281dd5cf5cfd2d87 $

PROG=	athalq
MAN=

CFLAGS+=	-I../../../../sys/contrib

SRCS=	main.c ar5210_ds.c ar5211_ds.c ar5212_ds.c ar5416_ds.c tdma.c
SRCS+=	ar9300_ds.c

.include <../Makefile.inc>

.include <bsd.prog.mk>
