# $FreeBSD: 1fd30a1354099e7256e17e2ae765cced4a415718 $

KYUA_VERSION=	0.13

KYUA_CONFDIR=	/etc/kyua
KYUA_DOCDIR=	/usr/share/doc/kyua
KYUA_EGDIR=	/usr/share/examples/kyua
KYUA_MISCDIR=	/usr/share/kyua/misc
KYUA_STOREDIR=	/usr/share/kyua/store

KYUA_SRCDIR=	${SRCTOP}/contrib/kyua
