# $FreeBSD: fa99e787fbea62fc68c22485d76da2e12ea43c32 $

ATF_TESTS_C+=	init_test
ATF_TESTS_C+=	fini_test
ATF_TESTS_CXX+=	cxx_constructors

WARNS?=		3

.if exists(${.CURDIR:H:H}/${MACHINE_ARCH})
CFLAGS+= -I${.CURDIR:H:H}/${MACHINE_ARCH}
.else
CFLAGS+= -I${.CURDIR:H:H}/${MACHINE_CPUARCH}
.endif
