# $FreeBSD: 3533fd3965061622f59b9875a289eb9c992cc4cf $

SUBDIR=		dso
TESTS_SUBDIRS=	dynamic
TESTS_SUBDIRS+=	dynamiclib
TESTS_SUBDIRS+=	dynamicpie
TESTS_SUBDIRS+=	static

SUBDIR_DEPEND_dynamiclib=dso

.include <bsd.test.mk>
