#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: 63aa832c99f4d81da72b425f2a28633f7ea3b443 $

PROG=	vis
SRCS=	vis.c foldit.c

.PATH: ${SRCTOP}/contrib/vis
CFLAGS+=	-I${SRCTOP}/contrib/vis

.include <bsd.prog.mk>
