# $FreeBSD: f0785245f7eebcb74b4ee6b50e2ad87b7fc02040 $

.PATH:		${SRCTOP}/sys/dev/iicbus
KMOD		= ds3231
SRCS		= ds3231.c bus_if.h clock_if.h device_if.h iicbus_if.h ofw_bus_if.h opt_platform.h

.include <bsd.kmod.mk>
