#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: a795582348c69827bf1d698fed94a1627e5be26b $

.include <src.opts.mk>

PACKAGE=	runtime

PROG=	xargs
SRCS=	xargs.c strnsubst.c

HAS_TESTS=
SUBDIR.${MK_TESTS}+= tests

.include <bsd.prog.mk>
