#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: 04cc44840a638accd4b43326faa2f77d945afbfc $

.include <src.opts.mk>

PROG=	xargs
SRCS=	xargs.c strnsubst.c

HAS_TESTS=
SUBDIR.${MK_TESTS}+= tests

.include <bsd.prog.mk>
