# $FreeBSD: releng/12.2/usr.bin/clang/llvm-cxxdump/Makefile 356462 2020-01-07 19:49:10Z dim $

PROG_CXX=	llvm-cxxdump
MAN=

SRCDIR=		llvm/tools/llvm-cxxdump
SRCS+=		Error.cpp
SRCS+=		llvm-cxxdump.cpp

.include "../llvm.prog.mk"
