# $FreeBSD: releng/12.2/usr.bin/clang/llvm-cxxfilt/Makefile 363494 2020-07-24 20:48:06Z dim $

PROG_CXX=	llvm-cxxfilt

SRCDIR=		llvm/tools/llvm-cxxfilt
SRCS+=		llvm-cxxfilt.cpp

.include "../llvm.prog.mk"
