# $FreeBSD: 7d5515480bc09d7870b22fb03a33e0d24542b015 $

SUBDIR = \
	hid \
	hidbus \
	hidmap \
	hidquirk \
	hidraw

SUBDIR += \
	hconf \
	hcons \
	hgame \
	hkbd \
	hms \
	hmt \
	hpen \
	hsctrl \
	ps4dshock \
	xb360gp

.include <bsd.subdir.mk>
