# $FreeBSD: 72368487bc6c0a6d62b240eaed14722e6cd62f7e $

SUBDIR = \
	hid \
	hidbus \
	hidmap \
	hidquirk \
	hidraw

SUBDIR += \
	bcm5974 \
	hconf \
	hcons \
	hgame \
	hkbd \
	hms \
	hmt \
	hpen \
	hsctrl \
	ietp \
	ps4dshock \
	xb360gp

.include <bsd.subdir.mk>
