# $FreeBSD: releng/12.2/sys/modules/iwmfw/Makefile 354927 2019-11-21 00:34:39Z markj $

SUBDIR=	iwm3160fw \
	iwm3168fw \
	iwm7260fw \
	iwm7265fw \
	iwm7265Dfw \
	iwm8000Cfw \
	iwm8265fw \
	iwm9000fw \
	iwm9260fw

.include <bsd.subdir.mk>
