#	@(#)Makefile	8.1 (Berkeley) 5/31/93
# $FreeBSD: releng/11.3/usr.bin/fortune/unstr/Makefile 321266 2017-07-20 00:50:01Z ngie $

PROG=	unstr
MAN=
CFLAGS+= -I${FORTUNE_SRC}/strfile

.include <bsd.prog.mk>
