# $FreeBSD: cfcfdca987a8374e91c4abda10f1e041ce3cdab3 $

PACKAGE=	tests

TESTSDIR=	${TESTSBASE}/usr.bin/bmake/suffixes/src_wild1

TAP_TESTS_SH=	legacy_test

${PACKAGE}FILES+=		Makefile.test
${PACKAGE}FILES+=		TEST1.a
${PACKAGE}FILES+=		TEST2.a
${PACKAGE}FILES+=		expected.status.1
${PACKAGE}FILES+=		expected.stderr.1
${PACKAGE}FILES+=		expected.stdout.1

.include <bsd.test.mk>
