# $FreeBSD: a2d806075d1aee99153a538dc1e495f635a7cdbf $

FILES=		${SRCTOP}/sys/contrib/dev/iwlwififw/LICENCE.iwlwifi_firmware
FILESDIR=	${SHAREDIR}/doc/legal
FILESNAME=	intel_iwlwifi_firmware.LICENCE

.include <bsd.prog.mk>
