# $FreeBSD: 9ad4b883015ca19b4f642ebbf252634b560d88bc $

.include <bsd.own.mk>

LIB=		pythagoras
SHLIB_MAJOR=	0

LIBDIR=		${TESTSBASE}/libexec/rtld-elf
SHLIBDIR=	${TESTSBASE}/libexec/rtld-elf

SRCS=		pythagoras.c

LIBADD=		m

.include <bsd.lib.mk>
