# $FreeBSD: 7c9583960953ea444a833637cfd7b4668e1404e4 $

.include <bsd.own.mk>

LIB=		pythagoras
SHLIB_MAJOR=	0

LIBDIR=		${TESTSBASE}/libexec/rtld-elf
SHLIBDIR=	${TESTSBASE}/libexec/rtld-elf

SRCS=		pythagoras.c

WARNS?=		6
LIBADD=		m

.include <bsd.lib.mk>
