# $FreeBSD: 36a84590be1dcd6e66953acaf65d63602d4a6562 $

.PATH: ${SRCTOP}/sys/net

KMOD=	if_vlan
SRCS=	if_vlan.c
SRCS+=	opt_inet.h opt_inet6.h opt_kern_tls.h opt_vlan.h opt_ratelimit.h

.include <bsd.kmod.mk>
