# $FreeBSD: 5e7aa49db19c68f72879127c228eb06a9f4190f0 $

.PATH:	${SRCTOP}/sys/dev/rccgpio
KMOD=	rccgpio
SRCS=	rccgpio.c
SRCS+=	device_if.h bus_if.h isa_if.h gpio_if.h opt_platform.h

.include <bsd.kmod.mk>
