#
# $FreeBSD: 7a6d7878a62ec78ebcf5ba88038beff0660d8adb $
#
# The pkg(8) repository configuration file for the installation DVD.
#

FreeBSD_install_cdrom: {
  url: "file:///dist/packages/${ABI}",
  mirror_type: "none",
  enabled: yes
}

FreeBSD: {
  enabled: no
}

