# $FreeBSD: releng/12.2/usr.bin/clang/llvm-modextract/Makefile 356462 2020-01-07 19:49:10Z dim $

PROG_CXX=	llvm-modextract
MAN=

SRCDIR=		llvm/tools/llvm-modextract
SRCS=		llvm-modextract.cpp

.include "../llvm.prog.mk"
