# $FreeBSD: 2c7f18c3632874069bb0eae37fecb899863ec356 $

PACKAGE=	tests

TAP_TESTS_SH=	legacy_test

${PACKAGE}FILES+=		regress.base64.out
${PACKAGE}FILES+=		regress.in
${PACKAGE}FILES+=		regress.sh
${PACKAGE}FILES+=		regress.traditional.out

.include <bsd.test.mk>
