# $FreeBSD: 8e6ea876bbe7bf01799fc86be9ee3136db675180 $
# All the dts files for omap4 systems we support.
DTS=	\
	omap4-duovero-parlor.dts \
        pandaboard.dts \
	pandaboard-es.dts

LINKS=	\
	${DTBDIR}/pandaboard.dtb ${DTBDIR}/omap4-panda.dtb \
	${DTBDIR}/pandaboard-es.dtb ${DTBDIR}/omap4-panda-es.dtb

.include <bsd.dtb.mk>
