# $FreeBSD: 036ec7fad4faa567153dea16368719b047cfbfe2 $
# All the dts files for omap4 systems we support.
DTS=	\
	omap4-duovero-parlor.dts \
	omap4-panda.dts \
	omap4-panda-es.dts

.include <bsd.dtb.mk>
