#	@(#)Makefile	8.1 (Berkeley) 6/5/93
# $FreeBSD: e9074074246581d694e6f097430052eab6f0b3cb $

# XXX MISSING:	connectives words
FILES=		README propernames web2 web2a freebsd
FILESDIR=	${BINDIR}/dict
SYMLINKS=	web2 ${FILESDIR}/words

.include <bsd.prog.mk>
