#	@(#)Makefile	8.1 (Berkeley) 6/9/93
# $FreeBSD: 18fd151b65990bbbf1fd75472805543ab7381486 $

PROG=	pmcstudy
MAN=	pmcstudy.8
SRCS= pmcstudy.c eval_expr.c
CFLAGS+= -Wall ${WERROR}

BINDIR= /usr/bin

.include <bsd.prog.mk>

