# $FreeBSD: releng/12.2/lib/libclang_rt/ubsan_minimal/Makefile 360545 2020-05-01 20:20:23Z dim $

.include <bsd.init.mk>

LIB=		clang_rt.ubsan_minimal-${CRTARCH}

SRCS+=		ubsan_minimal/ubsan_minimal_handlers.cpp

.include <bsd.lib.mk>
