# $FreeBSD: f939ab86332409d7bccbed2bdbb7e1577f3a8987 $

.include <bsd.own.mk>

# Change if the src tree you are compiling for is not in /usr/src
#SYSDIR=/usr/src/sys

PACKAGE=examples
FILESDIR=${SHAREDIR}/examples/kld/khelp
KMOD=	h_example
SRCS=	h_example.c

.include <bsd.kmod.mk>
