# $FreeBSD: 88cb691d8dda2d1cb62bfaca74015895f3193029 $

SUBDIR= distextract distfetch partedit scripts
SUBDIR_PARALLEL=
SCRIPTS= bsdinstall
MAN= bsdinstall.8
PACKAGE=	bsdinstall

.include <bsd.prog.mk>
