# $FreeBSD: cb51c4ea36ae7e8518a5a9e5b237a8221f458c94 $

.PATH: ${SRCTOP}/sys/arm/broadcom/bcm2835/

KMOD=	bcm283x_pwm
SRCS=	bcm2835_pwm.c

SRCS+= bus_if.h device_if.h ofw_bus_if.h

.include <bsd.kmod.mk>
