# $FreeBSD: 53e29c3891fb24c5e03e999384cea8da2c95e847 $

PACKAGE=	tests

.PATH: ${SRCTOP}/contrib/pjdfstest

BINDIR=		${TESTSBASE}/sys/pjdfstest
PROG=		pjdfstest
MAN=

CFLAGS+=	-I${.CURDIR:H}

.include <bsd.prog.mk>
