# $FreeBSD: e676cc036bad7b04281eaa718e7c770be541d312 $

PACKAGE=	tests

.PATH: ${SRCTOP}/contrib/pjdfstest

BINDIR=		${TESTSBASE}/sys/pjdfstest
PROG=		pjdfstest
MAN=

CFLAGS+=	-I${.CURDIR:H}

WARNS?=		6

.include <bsd.prog.mk>
