# $FreeBSD: 8fb1ad9532845f59a0c97a701dbb200bde4c70cb $

.if ${MK_ICONV} == "yes"
LIBC_NONSHARED_SRCS+=	\
	__iconv.c __iconv_free_list.c __iconv_get_list.c \
	iconv.c iconv_canonicalize.c iconv_close.c \
	iconv_open.c iconv_open_into.c \
	iconv_set_relocation_prefix.c iconvctl.c iconvlist.c
.endif
