# $FreeBSD: 4fda577b554af7685df97ed65848aed03b09e19a $
# $NetBSD: Makefile.inc,v 1.2 2008/10/25 22:27:35 apb Exp $

CODE=	ARMSCII
SEP=	-
ESUBDIR= AST
SED_EXP= 's/ARMSCII-x/ARMSCII-%%PART%%/'

.include "../Makefile.part"
