# $FreeBSD: cbc7f0c5257badf8671e14a582a05452121cdb77 $

.PATH: ${.CURDIR:H}/ctm_rmail

PROG=	ctm_dequeue
MAN=
SRCS=	ctm_dequeue.c error.c

CFLAGS+= -I${.CURDIR:H}/ctm_rmail

WARNS?=	1

.include <bsd.prog.mk>
