# $FreeBSD: ef40ab9a968c8beab5b63bc71377ccc2db15a383 $

PACKAGE=	tests

TESTSDIR=	${TESTSBASE}/usr.bin/bmake/sysmk/t0/mk

${PACKAGE}FILES+=	sys.mk.test

${PACKAGE}FILESNAME_sys.mk.test=	sys.mk

.include <bsd.test.mk>
