# Make `routed` tools for BSD/OS
# $Revision: 1.6 $
# $FreeBSD: a9893a988537907c36c34f9983abcebc87d4be3e $

PACKAGE=runtime
PROG=	rtquery
MAN=	rtquery.8
LIBADD=	md
WARNS?=	3
NO_WARRAY_BOUNDS=

.include <bsd.prog.mk>
