# $FreeBSD: 216bfa8a4fd79644140f1b39fb9a1a3f5a836afd $

NATIVE_EMULATION= elf_i386_fbsd

SRCS+=		e${NATIVE_EMULATION}.c
CLEANFILES+=	e${NATIVE_EMULATION}.c
e${NATIVE_EMULATION}.c: emulparams/${NATIVE_EMULATION}.sh emultempl/elf32.em \
    scripttempl/elf.sc genscripts.sh stringify.sed
	sh ${.CURDIR}/genscripts.sh ${SRCDIR}/ld ${LIBSEARCHPATH} \
	    ${TOOLS_PREFIX}/usr \
	    ${HOST} ${TARGET_TUPLE} ${TARGET_TUPLE} \
	    ${NATIVE_EMULATION} "" no ${NATIVE_EMULATION} ${TARGET_TUPLE}
