# $FreeBSD: bbd869715fa41497fc5b71b40deea462aa91104b $

SRCS+= sysfake.c
CLEANFILES+= sysfake.c

sysfake.c: ${.CURDIR}/../../sys/kern/syscalls.master
	sh ${.CURDIR}/../../tools/tools/shlib-compat/makesyscalls-fake.sh \
		${.CURDIR}/../../sys/kern/syscalls.master > ${.TARGET}

