# $FreeBSD: 7ef2c8e15daca53aee915e92f176a02c1063acd0 $

NEED_COMPAT=	32
.include <bsd.compat.mk>

PROG=	ldd32
MAN=
MLINKS=	ldd.1 ldd32.1

.PATH:	${SRCTOP}/usr.bin/ldd
.include "${SRCTOP}/usr.bin/ldd/Makefile"
