# $FreeBSD: 8684293ca9e25ae754f622d32d26d12d6a6d8da3 $

.PATH: ${SRCTOP}/sys/dev/ata/chipsets

KMOD=	ataacerlabs
SRCS=	ata-acerlabs.c
SRCS+=	ata_if.h bus_if.h device_if.h pci_if.h

.include <bsd.kmod.mk>
