# $FreeBSD: 096c9c3528b5d9089cfa237541c0556608c628d3 $
# Build modules specific to freescale/nxp imx-family SoCs.

SUBDIR = \
	../ffec \
	imx6_ahci \
	imx6_snvs \
	imx_i2c \
	imx_spi \
	imx_wdog \
	
.include <bsd.subdir.mk>
