# $FreeBSD: 64bd6502f1f6e766de06cff4e625571b91eb56d0 $

.PATH: ${SRCTOP}/sys/dev/ata/chipsets

KMOD=	atanetcell
SRCS=	ata-netcell.c
SRCS+=	ata_if.h bus_if.h device_if.h pci_if.h

.include <bsd.kmod.mk>
