#!/bin/sh
#
# $FreeBSD: 52734b1dd8e898bfdf556669eaac90fa13d86deb $
#

EMBEDDED_TARGET_ARCH="riscv64"
EMBEDDED_TARGET="riscv"
EMBEDDEDBUILD=1
FAT_SIZE="54m -b 8m"
FAT_TYPE="16"
IMAGE_SIZE="3072M"
KERNEL="GENERIC"
MD_ARGS="-x 63 -y 255"
NODOC=1
PART_SCHEME="GPT"
export BOARDNAME="GENERICSD"
