#!/bin/sh
#
# $FreeBSD: 057babf769c177bdb4aed5abd39e22650182463d $
#

EMBEDDED_TARGET_ARCH="riscv64"
EMBEDDED_TARGET="riscv"
EMBEDDEDBUILD=1
FAT_SIZE="54m -b 8m"
FAT_TYPE="16"
IMAGE_SIZE="5120M"
KERNEL="GENERIC"
MD_ARGS="-x 63 -y 255"
PART_SCHEME="GPT"
export BOARDNAME="GENERICSD"
