#	From: @(#)Makefile	6.3 (Berkeley) 6/8/93
# $FreeBSD: 00e1e3d87a3edeba86ccae3f0f16bf0acf19306f $

VOLUME=	papers
DOC=	malloc
SRCS=	abs.ms intro.ms kernel.ms malloc.ms problems.ms alternatives.ms \
	performance.ms implementation.ms conclusion.ms
MACROS=	-ms

.include <bsd.doc.mk>
