#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: releng/11.3/usr.bin/vmstat/Makefile 339392 2018-10-16 20:53:16Z jhb $

PROG=	vmstat
MAN=	vmstat.8
LIBADD=	devstat kvm memstat xo util

WARNS?=	6

.include <bsd.prog.mk>
