# $FreeBSD: 336052712738fde09b287bf2fc7d53034156caf5 $

.PATH: ${SRCTOP}/sys/dev/ata/chipsets

KMOD=	atacenatek
SRCS=	ata-cenatek.c
SRCS+=	ata_if.h bus_if.h device_if.h pci_if.h

.include <bsd.kmod.mk>
