# $FreeBSD: releng/12.2/lib/libclang_rt/asan-preinit/Makefile 360545 2020-05-01 20:20:23Z dim $

.include <bsd.init.mk>

LIB=		clang_rt.asan-preinit-${CRTARCH}

SRCS+=		asan/asan_preinit.cpp

.include <bsd.lib.mk>
