# $FreeBSD: 1569e7e495698d1d986b043c32340a43465f95d4 $

SUBDIR= include share

FILESDIR=	${LIBEXECDIR}/bsdconfig/090.timezone
FILES=		INDEX USAGE

SCRIPTSDIR=	${FILESDIR}
SCRIPTS=	timezone

.include <bsd.prog.mk>
