#	From: @(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: 61731b8746d27aeeabe3075190015734928b7eed $

.include <src.opts.mk>

PACKAGE=acct

PROG=	lastcomm
SRCS=	lastcomm.c readrec.c

HAS_TESTS=
SUBDIR.${MK_TESTS}+= tests

.include <bsd.prog.mk>
