# $FreeBSD: ab8a3562fc6d03558a370d9eb401c6a136904ad2 $

.PATH:		${SRCTOP}/sys/dev/viapm
KMOD		= viapm
SRCS		= device_if.h bus_if.h iicbb_if.h isa_if.h pci_if.h smbus_if.h \
		  opt_isa.h viapm.c

.include <bsd.kmod.mk>
