# Makefile for building the sample syscall module
# $FreeBSD: 94996fe334cbe7c2a0c480e050afad81b15284a1 $

PACKAGE=examples
FILESDIR=${SHAREDIR}/examples/kld/${KMOD}
KMOD=	syscall
SRCS=	syscall.c

.include <bsd.kmod.mk>
