# Makefile for simple caller of syscall
# $FreeBSD: f8fecdebba8f95b85bbe8beebe1de4ffd5b5fcb2 $

PACKAGE=examples
FILESDIR=${SHAREDIR}/examples/kld/test
PROG=	call
MAN=
WARNS?=	5

.include <bsd.prog.mk>
