# $FreeBSD: 47a679fe2a245302cdd77c6fa043d421117b16e8 $

.PATH: ${SRCTOP}/sys/dev/sis

KMOD=	if_sis
SRCS=	if_sis.c device_if.h bus_if.h pci_if.h
SRCS+=	miibus_if.h opt_platform.h

.include <bsd.kmod.mk>
