# $FreeBSD: b0ae002fd5e911a9ed09ea0442687256a95d808f $

LIB=	calendar

SRCS=	calendar.c easter.c
INCS=	calendar.h

MAN=	calendar.3

MLINKS=	calendar.3 easterg.3 calendar.3 easterog.3 calendar.3 easteroj.3 \
	calendar.3 gdate.3 calendar.3 jdate.3 \
	calendar.3 ndaysg.3 calendar.3 ndaysj.3 \
	calendar.3 week.3 calendar.3 weekday.3

.include <bsd.lib.mk>
