# $FreeBSD: d217a10a7f5c1cd17088ab07d6d7d2822962ed9d $

PACKAGE=	lib${LIB}
LIB=	calendar

SRCS=	calendar.c easter.c
INCS=	calendar.h

MAN=	calendar.3

MLINKS=	calendar.3 easterg.3 calendar.3 easterog.3 calendar.3 easteroj.3 \
	calendar.3 gdate.3 calendar.3 jdate.3 \
	calendar.3 ndaysg.3 calendar.3 ndaysj.3 \
	calendar.3 week.3 calendar.3 weekday.3

.include <bsd.lib.mk>
