# $FreeBSD: 1cf610cb5939da821260df462641380d12d987b1 $

.include <src.opts.mk>

PACKAGE=runtime
PROG=		mdconfig
MAN=		mdconfig.8

LIBADD=		util geom

HAS_TESTS=
SUBDIR.${MK_TESTS}+= tests

.include <bsd.prog.mk>
