# $FreeBSD: 5334743683724b39552cad684737d05d06c82d83 $

PACKAGE=	FreeBSD-rdma

SUBDIR= \
asyncwatch \
devinfo \
devices \
rc_pingpong \
srq_pingpong \
uc_pingpong \
ud_pingpong

.include <bsd.subdir.mk>
