#!/bin/sh
#
# $FreeBSD: 4e0f02c0e76c306a0aab64ca8b168e797b23fd26 $
#

. ${WORLDDIR}/release/tools/vagrant.conf

export VM_EXTRA_PACKAGES="${VM_EXTRA_PACKAGES} open-vm-tools-nox11"

vm_extra_pre_umount () {
	# VMWare first boot pkgs
	echo 'firstboot_pkgs_list="sudo rsync open-vm-tools-nox11"' >> ${DESTDIR}/etc/rc.conf

	echo 'vmware_guest_vmblock_enable="YES"' >> ${DESTDIR}/etc/rc.conf
	echo 'vmware_guest_vmhgfs_enable="YES"' >> ${DESTDIR}/etc/rc.conf
	echo 'vmware_guest_vmmemctl_enable="YES"' >> ${DESTDIR}/etc/rc.conf
	echo 'vmware_guest_vmxnet_enable="YES"' >> ${DESTDIR}/etc/rc.conf
	echo 'vmware_guestd_enable="YES"' >> ${DESTDIR}/etc/rc.conf

	# Setup the Vagrant common items
	vagrant_common
	rm -f ${DESTDIR}/etc/resolv.conf
}
