# $FreeBSD: a653507f54b00e890eb527bf91dd61017861f1fa $

PACKAGE=utilities
FILESDIR= ${SHAREDIR}/examples/smbfs
FILES=	dot.nsmbrc

.PATH: ${SRCTOP}/contrib/smbfs/examples

SUBDIR=	print

.include <bsd.prog.mk>
