# $FreeBSD: e8e5f1cc0d323275fa02c4c05834546d2ad660b9 $

PACKAGE=examples
FILESDIR= ${SHAREDIR}/examples/smbfs
FILES=	dot.nsmbrc

.PATH: ${SRCTOP}/contrib/smbfs/examples

SUBDIR=	print

.include <bsd.prog.mk>
