#!/bin/sh
#
# $FreeBSD: c900f31255e3e07a4b27b407b349344ab5a64986 $
#
#  hpvf - Convert GIF files into HP/PCL, then print
#  Installed in /usr/local/libexec/hpvf

giftopnm | ppmtopgm | pgmtopbm | pbmtolj -resolution 300 \
    && exit 0 \
    || exit 2
