# $FreeBSD: 9c4624af3a4c10db3a97b3e3294622ecafcfd22a $

PACKAGE=	tests

ATF_TESTS_SH=	fstyp_test

${PACKAGE}FILES+=	dfr-01-xfat.img.bz2
${PACKAGE}FILES+=	ext2.img.bz2
${PACKAGE}FILES+=	ext3.img.bz2
${PACKAGE}FILES+=	ext4.img.bz2
${PACKAGE}FILES+=	ext4_with_label.img.bz2
${PACKAGE}FILES+=	ntfs.img.bz2
${PACKAGE}FILES+=	ntfs_with_label.img.bz2

.include <bsd.test.mk>
