/* $FreeBSD: af1f80bb599aa75dc5ce278f79d27abcb2dc96df $ */
#define GSSAPI 1
#define HAVE_DECL_GSS_C_NT_HOSTBASED_SERVICE 1
#define HAVE_GSSAPI_GSSAPI_H 1
#define HAVE_GSSAPI_GSSAPI_KRB5_H 1
#define HAVE_GSSAPI_H 1
#define HAVE_KRB5_CC_NEW_UNIQUE 1
#define HAVE_KRB5_FREE_ERROR_MESSAGE 1
#define HAVE_KRB5_GET_ERROR_MESSAGE 1
#define HEIMDAL 1
#define KRB5 1
