#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: c366d574e0902971455f4ce8999b902910a39f66 $

.include <src.opts.mk>

PROG=	split

LIBADD=	util

HAS_TESTS=		yes
SUBDIR.${MK_TESTS}+=	tests

.include <bsd.prog.mk>
