# $FreeBSD: 5a15ef3c9da6ff68e7eb876b11f8fb02aeba7c86 $

PROG=	kbdcontrol
MAN=	kbdcontrol.1 kbdmap.5
MLINKS= kbdmap.5 keymap.5
SRCS=	kbdcontrol.c lex.l

WARNS?=	4
CFLAGS+= -I${.CURDIR}

.include <bsd.prog.mk>
