# $FreeBSD: 22710f3d933de1a4f4d240de01d2a24a7368be9f $

.include <bsd.own.mk>

PACKAGE=lib${LIB}
LIB=	netbsd

CFLAGS+=	-I${.CURDIR}

SRCS+=	efun.c sockaddr_snprintf.c strsuftoll.c util.c util.h

INTERNALLIB=

.include <bsd.lib.mk>
