# $FreeBSD: releng/12.2/sys/modules/itwd/Makefile 353647 2019-10-16 14:57:38Z avg $

.PATH: ${SRCTOP}/sys/dev/itwd

KMOD=	itwd
SRCS=	itwd.c
SRCS+=	device_if.h bus_if.h isa_if.h

.include <bsd.kmod.mk>
