# $FreeBSD: f35c07c45829f17f00ff8b64189d5a9472c3b360 $

PACKAGE=	tests

TESTSDIR=	${TESTSBASE}/usr.bin/bmake/sysmk/t2/mk

${PACKAGE}FILES+=	sys.mk.test

${PACKAGE}FILESNAME_sys.mk.test=	sys.mk

.include <bsd.test.mk>
