# $FreeBSD: e370fad97df45e5f434bd7ec958c1167194a2b8e $

PACKAGE=	tests

TESTSDIR=	${TESTSBASE}/sys/netgraph
BINDIR=		${TESTSDIR}

TAP_TESTS_SH+=	ng_macfilter_test

TEST_METADATA.runtests+= required_user="root"

MAN=

.include <bsd.test.mk>
