# $FreeBSD: 8f1d6d9b9c4150c53de2e152f9511cb85183e6d1 $

FILES=		${SRCTOP}/sys/contrib/dev/rtw88fw/LICENCE.rtlwifi_firmware.txt
FILESDIR=	${SHAREDIR}/doc/legal
FILESNAME=	realtek_rtw88_firmware.LICENCE

.include <bsd.prog.mk>
