# $FreeBSD: 082d5ed877b3a965a6c7dd98283a86d3df10c0f0 $

.PATH: ${SRCTOP}/sys/netinet ${SRCTOP}/sys/netinet6

KMOD=	ip_mroute

SRCS=	ip_mroute.c
SRCS+=	opt_inet.h opt_mrouting.h

.include <bsd.kmod.mk>
