#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: dc639af6e2e86862febbddbfe07e144328a0e33c $

PROG=	ctags
SRCS=	C.c ctags.c fortran.c lisp.c print.c tree.c yacc.c
CFLAGS+=-I${.CURDIR}

.include <bsd.prog.mk>
