#	from: @(#)Makefile	5.2 (Berkeley) 5/11/90
# $FreeBSD: 3c8e51c000c3cbff6675fabbc9ddfd4ae57db41b $

PROG=	rpcinfo
SRCS=	rpcinfo.c
MAN=	rpcinfo.8

CFLAGS+= -DPORTMAP

WARNS?=	2

.include <bsd.prog.mk>
