# $FreeBSD: a0b0f43dd65385c71d7d7cf0928b89c930a6ad5c $

.PATH:		${SRCTOP}/sys/dev/iicbus
KMOD		= ds1307
SRCS		= ds1307.c bus_if.h clock_if.h device_if.h iicbus_if.h ofw_bus_if.h opt_platform.h

.include <bsd.kmod.mk>
