# Cronyx Id: sbin.sconfig.Makefile,v 1.1.4.1 2003/02/17 12:51:24 rik Exp $
# $FreeBSD: 3a7e4b2c7b828553ca9dedcd6fa0df65b0cdc884 $

PACKAGE=utilities
PROG=	sconfig
MAN=	sconfig.8
MANSUBDIR= /i386
WARNS?=	2

.include <bsd.prog.mk>
