# $FreeBSD: a09697a29d0d85be66d7b59dfc186be44b868a89 $

SUBDIR=	media packages

FILESDIR=	${SHAREDIR}/bsdconfig
FILES=		common.subr device.subr dialog.subr geom.subr keymap.subr \
		mustberoot.subr script.subr strings.subr struct.subr \
		sysrc.subr variable.subr

.include <bsd.prog.mk>
