# $FreeBSD: 9910365a5b0a0c352ed5afce7471771281158b34 $

.include <src.opts.mk>

SUBDIR.${MK_DIALOG}+=	dialog
SUBDIR.${MK_GNU_DIFF}+=	diff3
SUBDIR.${MK_TESTS}+=	tests

SUBDIR_PARALLEL=

.include <bsd.subdir.mk>
