# $FreeBSD: 01280c4ae58d8dd7d1830f668c8ae058801f067f $

.include <bsd.init.mk>

LIB=		clang_rt.xray-basic-${CRTARCH}

SRCS+=		xray/xray_basic_flags.cpp
SRCS+=		xray/xray_basic_logging.cpp

.include <bsd.lib.mk>
