# $FreeBSD: releng/12.2/lib/libclang_rt/xray-basic/Makefile 360545 2020-05-01 20:20:23Z dim $

.include <bsd.init.mk>

LIB=		clang_rt.xray-basic-${CRTARCH}

SRCS+=		xray/xray_basic_flags.cpp
SRCS+=		xray/xray_basic_logging.cpp

.include <bsd.lib.mk>
