# $FreeBSD: 6dbb8728df4a61dc2c9bd40060e6c7fc077e433a $

PACKAGE=	tests

TESTSDIR=	${TESTSBASE}/usr.bin/bmake/shell/path

TAP_TESTS_SH=	legacy_test

${PACKAGE}FILES+=		Makefile.test
${PACKAGE}FILES+=		expected.status.1
${PACKAGE}FILES+=		expected.status.2
${PACKAGE}FILES+=		expected.stderr.1
${PACKAGE}FILES+=		expected.stderr.2
${PACKAGE}FILES+=		expected.stdout.1
${PACKAGE}FILES+=		expected.stdout.2
${PACKAGE}FILES+=		sh

.include <bsd.test.mk>
