# $Id: Makefile,v 1.7 2003/08/14 20:06:22 max Exp $
# $FreeBSD: 8f17e02f0045d8ca327253e153a6ee4e599c5588 $

PROG=		l2control
MAN=		l2control.8
SRCS=		l2cap.c l2control.c
WARNS?=		2

LIBADD=		bluetooth

.include <bsd.prog.mk>
