# $Id: Makefile,v 1.7 2003/08/14 20:06:22 max Exp $
# $FreeBSD: 8dab32051c04b0e08a2b318959f932954a25fa8c $

PACKAGE=	bluetooth
PROG=		l2control
MAN=		l2control.8
SRCS=		l2cap.c l2control.c
WARNS?=		2

LIBADD=		bluetooth

.include <bsd.prog.mk>
