# $FreeBSD: 9f18bc1c6353c6d566df81a99e3a8f1667c8d448 $

PROG_CXX=	clang-tblgen
MAN=

SRCDIR=		clang/utils/TableGen
SRCS+=		ASTTableGen.cpp
SRCS+=		ClangASTNodesEmitter.cpp
SRCS+=		ClangASTPropertiesEmitter.cpp
SRCS+=		ClangAttrEmitter.cpp
SRCS+=		ClangCommentCommandInfoEmitter.cpp
SRCS+=		ClangCommentHTMLNamedCharacterReferenceEmitter.cpp
SRCS+=		ClangCommentHTMLTagsEmitter.cpp
SRCS+=		ClangDataCollectorsEmitter.cpp
SRCS+=		ClangDiagnosticsEmitter.cpp
SRCS+=		ClangOpcodesEmitter.cpp
SRCS+=		ClangOpenCLBuiltinEmitter.cpp
SRCS+=		ClangOptionDocEmitter.cpp
SRCS+=		ClangSACheckersEmitter.cpp
SRCS+=		ClangSyntaxEmitter.cpp
SRCS+=		ClangTypeNodesEmitter.cpp
SRCS+=		MveEmitter.cpp
SRCS+=		NeonEmitter.cpp
SRCS+=		RISCVVEmitter.cpp
SRCS+=		SveEmitter.cpp
SRCS+=		TableGen.cpp

.include "../llvm.prog.mk"
