# $FreeBSD: ce30af05ac5f2071b042e932af5c056ec147c506 $

PROG_CXX=	clang-tblgen
MAN=

SRCDIR=		clang/utils/TableGen
SRCS+=		ASTTableGen.cpp
SRCS+=		ClangASTNodesEmitter.cpp
SRCS+=		ClangASTPropertiesEmitter.cpp
SRCS+=		ClangAttrEmitter.cpp
SRCS+=		ClangCommentCommandInfoEmitter.cpp
SRCS+=		ClangCommentHTMLNamedCharacterReferenceEmitter.cpp
SRCS+=		ClangCommentHTMLTagsEmitter.cpp
SRCS+=		ClangDataCollectorsEmitter.cpp
SRCS+=		ClangDiagnosticsEmitter.cpp
SRCS+=		ClangOpcodesEmitter.cpp
SRCS+=		ClangOpenCLBuiltinEmitter.cpp
SRCS+=		ClangOptionDocEmitter.cpp
SRCS+=		ClangSACheckersEmitter.cpp
SRCS+=		ClangTypeNodesEmitter.cpp
SRCS+=		MveEmitter.cpp
SRCS+=		NeonEmitter.cpp
SRCS+=		TableGen.cpp

.include "../llvm.prog.mk"
