# $FreeBSD: releng/12.2/usr.bin/clang/llvm-mc/Makefile 356462 2020-01-07 19:49:10Z dim $

PROG_CXX=	llvm-mc
MAN=

SRCDIR=		llvm/tools/llvm-mc
SRCS+=		Disassembler.cpp
SRCS+=		llvm-mc.cpp

LIBADD+=	z

.include "../llvm.prog.mk"
