# $FreeBSD: 772efd38266f03bd872a9af3d5e9933a8afeac39 $

CONFS=		include_ldap \
		include_nis \
		include_nis_nullfs \
		special_hosts \
		special_media \
		special_noauto \
		special_null

NO_OBJ=
CONFDIR=	/etc/autofs
CONFMODE=	755

.include <bsd.prog.mk>
