#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: bcde84f0255adad5eb445ede3cf77aafd3dce4a8 $

.include <src.opts.mk>

PROG=	cmp
SRCS=	cmp.c link.c misc.c regular.c special.c

HAS_TESTS=
SUBDIR.${MK_TESTS}+= tests

.include <bsd.prog.mk>
