# $FreeBSD: feb543dad24332a8dea84ce3435c9d94825a77a5 $

.include <bsd.own.mk>

NETBSD_ATF_TESTS_C=	mktime_test
NETBSD_ATF_TESTS_C+=	strptime_test

.include "../Makefile.netbsd-tests"

.include <bsd.test.mk>
