# $FreeBSD: 7d6576753b37b93367e9543d9ae5b7f11e956ae7 $

.PATH:	${SRCTOP}/sys/dev/acpi_support

KMOD=	acpi_toshiba
SRCS=	acpi_toshiba.c opt_acpi.h acpi_if.h bus_if.h device_if.h

.include <bsd.kmod.mk>
