# $FreeBSD: 128e5118bc4101a61d2fca1a280569f18bab3f04 $
#
# Test the -V option
#

FOO=	foo
FOOBAR=	${FOO}bar

test1:
	@echo "-V FOOBAR"
	@${MAKE} -V FOOBAR

test2:
	@echo '-V "$${FOOBAR}"'
	@${MAKE} -V '$${FOOBAR}'
