# $FreeBSD: releng/11.3/usr.sbin/ntp/doc/drivers/icons/Makefile 319191 2017-05-30 05:15:09Z ngie $

.include <src.opts.mk>

FILESDIR=	${SHAREDIR}/doc/ntp/drivers/icons

.if ${MK_HTML} != "no"
FILES=	home.gif mail2.gif
.endif

.PATH: ${SRCTOP}/contrib/ntp/html/drivers/icons

.include <bsd.prog.mk>
