# $FreeBSD: 55746bedb7ead9d443379115f84bcaac03cea9c5 $

.include <src.opts.mk>

FILESDIR=	${SHAREDIR}/doc/ntp/drivers/icons

.if ${MK_HTML} != "no"
FILES=	home.gif mail2.gif
.endif

.PATH: ${SRCTOP}/contrib/ntp/html/drivers/icons

.include <bsd.prog.mk>
