#	From: @(#)Makefile	8.1 (Berkeley) 6/8/93
# $FreeBSD: f84456866b21ee991e6e27eecbb28bab533ef9cd $

VOLUME=		smm/12.timed
SRCS=		timed.ms
EXTRA=		date loop time unused
MACROS=		-ms
USE_SOELIM=
USE_TBL=

.include <bsd.doc.mk>
