# $FreeBSD: e13a43cf7eaad0ad8cdf892c3b2ee85498867c4e $

.PATH:	${SRCTOP}/sys/dev/acpi_support

KMOD=	acpi_panasonic
SRCS=	acpi_panasonic.c opt_acpi.h acpi_if.h bus_if.h device_if.h

.include <bsd.kmod.mk>
