# $FreeBSD: 89e415603bb913a5d364b2b866d23548e9444e04 $

.PATH:  ${.CURDIR}/../../../../sys/dev/ath/ath_hal

PROG=	ath_ee_v4k_print
SRCS=	main.c eeprom.c v4k.c
MAN=

.include <../Makefile.inc>

.include <bsd.prog.mk>
