# $FreeBSD: 18b0276b7296523e62b75e5cc2a2b393ca10ebce $

TESTSRC:=	${SRCTOP}/contrib/netbsd-tests/${RELDIR:C/libc\/tests/libc/}

TESTSDIR:=	${TESTSBASE}/${RELDIR:C/libc\/tests/libc/}

WARNS?=		2

.include <netbsd-tests.test.mk>
