# $FreeBSD: releng/12.2/usr.bin/clang/llvm-lto/Makefile 356462 2020-01-07 19:49:10Z dim $

PROG_CXX=	llvm-lto
MAN=

SRCDIR=		llvm/tools/llvm-lto
SRCS=		llvm-lto.cpp

LIBADD+=	z

.include "../llvm.prog.mk"
