# $FreeBSD: releng/12.2/usr.bin/clang/lldb-tblgen/Makefile 360545 2020-05-01 20:20:23Z dim $

PROG_CXX=	lldb-tblgen
MAN=

SRCDIR=		lldb/utils/TableGen
SRCS+=		LLDBOptionDefEmitter.cpp
SRCS+=		LLDBPropertyDefEmitter.cpp
SRCS+=		LLDBTableGen.cpp
SRCS+=		LLDBTableGenUtils.cpp

.include "../llvm.prog.mk"
