#	From: @(#)Makefile	1.8 (Berkeley) 6/8/93
# $FreeBSD: 02908918a47426c62b0a4dfedf029d48155098cd $

VOLUME=		papers
DOC=		kernmalloc
SRCS=		kernmalloc.t appendix.ms
EXTRA=		alloc.fig usage.tbl
MACROS=		-ms
USE_EQN=
USE_PIC=
USE_SOELIM=
USE_TBL=

.include <bsd.doc.mk>
