# $FreeBSD: 4e4d361c8efb93d1216043a19b18ad403fc1378f $
# $Whistle: Makefile,v 1.1 1999/01/24 06:48:07 archie Exp $

.PATH: ${SRCTOP}/sys/net

KMOD=	ng_vjc
SRCS= 	ng_vjc.c slcompress.c

.include <bsd.kmod.mk>
