#	@(#)Makefile	8.1 (Berkeley) 5/31/93
# $FreeBSD: 5409d962e3ed890329c8ba02be2f6ee66ad134b0 $

PACKAGE=	games

PROG=	caesar
LIBADD=	m
SCRIPTS=rot13.sh
MAN=	caesar.6
MLINKS=	caesar.6 rot13.6

.include <bsd.prog.mk>
