# $FreeBSD: 6d77f25c5e9e7d01d30a8a9c8757376b44eed34f $

FILESDIR=	${SHAREDIR}/bsdconfig/networking
FILES=		common.subr device.subr hostname.subr ipaddr.subr media.subr \
		netmask.subr resolv.subr routing.subr services.subr

.include <bsd.prog.mk>
