# $FreeBSD: 9ee3649071b209b044b95f781ff70f5d6ef316f3 $

S.yes+=		userboot
S.yes+=		i386

SUBDIR_DEPEND_userboot+=	${INTERP_DEPENDS}
# These won't get tacked on in an amd64 build
SUBDIR_DEPEND_i386+=	${LIB32DEPENDS} ${INTERP_DEPENDS}
