# $FreeBSD: 740d3594cdcf39c00ba8c2278385b3954e4ea571 $

PROG=	npestats
SRCS=	main.c npestats.c
BINDIR=	/usr/local/bin
MAN=
LIBADD=	bsdstat
CFLAGS+=-I${.CURDIR}/../../../../lib/libbsdstat/

.include <bsd.prog.mk>
