# $FreeBSD: 06029b7a90d0c24cfca2351404389591fc636f52 $

BINDIR		?= ${HOME}/bin
BINOWN		?= ${USER}
BINGRP		?= ${USER}
SCRIPTS		 = hcomp.pl

MANDIR		?= ${HOME}/man/man
MANOWN		?= ${USER}
MANGRP		?= ${USER}
MAN		 = # empty

.include <bsd.prog.mk>
