# $FreeBSD: a9f79d3d81e191f006036d51c6c8b4954c4231a3 $

.include <src.opts.mk>

PROG=	diff
SRCS=	diff.c diffdir.c diffreg.c xmalloc.c pr.c

HAS_TESTS=
SUBDIR.${MK_TESTS}+= tests

.include <bsd.prog.mk>
