# $FreeBSD: c48e1759af9a16c67651eb7ac794aaf34bf1ec35 $

PACKAGE=	tests

TESTSDIR=	${TESTSBASE}/usr.bin/bmake/syntax/semi

TAP_TESTS_SH=	legacy_test

${PACKAGE}FILES+=		Makefile.test
${PACKAGE}FILES+=		expected.status.1
${PACKAGE}FILES+=		expected.status.2
${PACKAGE}FILES+=		expected.stderr.1
${PACKAGE}FILES+=		expected.stderr.2
${PACKAGE}FILES+=		expected.stdout.1
${PACKAGE}FILES+=		expected.stdout.2

.include <bsd.test.mk>
