# $FreeBSD: 97271106d642e7a672bcc99246284af3cfc646c3 $

PACKAGE=	tests

ATF_TESTS_SH=	soelim_test

${PACKAGE}FILES+=		nonexisting.in \
		basic.in \
		basic \
		basic.out \
		basic-with-space.in \
		basic-with-space.out

.include <bsd.test.mk>
