#	From: @(#)Makefile	8.1 (Berkeley) 6/8/93
# $FreeBSD: d63aae2d877deaaab47e1532f3e14df356b5ba3d $

VOLUME=		smm/05.fastfs
SRCS=		0.t 1.t 2.t 3.t 4.t 5.t 6.t
MACROS=		-ms
USE_TBL=
USE_EQN=

.include <bsd.doc.mk>
