# $FreeBSD: 1f731ff27114e239e20bb2582a40281b951c7e43 $

.PATH: ${SRCTOP}/sys/dev/ata/chipsets

KMOD=	ataserverworks
SRCS=	ata-serverworks.c
SRCS+=	ata_if.h bus_if.h device_if.h pci_if.h

.include <bsd.kmod.mk>
