#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: 4cf4550801c6c8fdaef7dfc3713bd6a08fbcfce1 $

.include <src.opts.mk>

PACKAGE=	runtime
PROG=	sed
SRCS=	compile.c main.c misc.c process.c

HAS_TESTS=
SUBDIR.${MK_TESTS}+= tests

.include <bsd.prog.mk>
