#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: 2a90fb10153ff8aefba57e3c22bbcbb06f34f667 $

.include <src.opts.mk>

PROG=	sed
SRCS=	compile.c main.c misc.c process.c

HAS_TESTS=
SUBDIR.${MK_TESTS}+= tests

.include <bsd.prog.mk>
