# $FreeBSD: 365c99b3ddbe2f64e3663dd1664d1689710fbd52 $
#
# Author: Gleb Smirnoff <glebius@freebsd.org>
#

.PATH: ${SRCTOP}/sys/netgraph/netflow

KMOD=   ng_netflow
SRCS=   ng_netflow.c netflow.c netflow_v9.c opt_inet6.h opt_route.h

.include <bsd.kmod.mk>
