#!/bin/sh
#
# $FreeBSD: 305a5765afc549fa72474360eee31b9e27f4dd48 $

GREP=grep
mountpoint=$(df . | tail -1 | awk '{print $6}')
fs=$(mount -p | awk '$2 == "'$mountpoint'" { print toupper($3) }')
os=FreeBSD
