# $FreeBSD: 536d8b88200ce23f0ff58bdcbb0d304b2d0dfac8 $

.PATH:	${SRCTOP}/sys/xdr
KMOD=	xdr
SRCS=	xdr.c \
	xdr_array.c \
	xdr_mbuf.c \
	xdr_mem.c \
	xdr_reference.c \
	xdr_sizeof.c

.include <bsd.kmod.mk>
