# $FreeBSD: releng/12.2/sys/modules/xdr/Makefile 360036 2020-04-17 06:04:20Z glebius $

.PATH:	${SRCTOP}/sys/xdr
KMOD=	xdr
SRCS=	xdr.c \
	xdr_array.c \
	xdr_mbuf.c \
	xdr_mem.c \
	xdr_reference.c \
	xdr_sizeof.c

.include <bsd.kmod.mk>
