# $FreeBSD: ba17ab997ae30c360a48bab95298223d4b206aae $

.include "../Makefile.inc0"

.PATH: ${SRCDIR}/gas/doc \
	${SRCDIR}/ld \
	${SRCDIR}/binutils/doc

MAN=	ld.7 ldint.7 as.7 binutils.7

.include <bsd.prog.mk>
