#	@(#)Makefile	8.1 (Berkeley) 6/5/93
# $FreeBSD: fc7e38be03cd86017bcb0de37e968da002949549 $

PACKAGE=runtime
PROG=	shutdown
MAN=	shutdown.8
LINKS=	${BINDIR}/shutdown ${BINDIR}/poweroff
MLINKS=	shutdown.8 poweroff.8

BINOWN=	root
BINGRP=	operator
BINMODE=4554

.include <bsd.prog.mk>
