# $FreeBSD: bd6f7cf5ad5c1d1d3628bd246f200485eacf61d4 $

TESTSDIR=	${TESTSBASE}/cddl/usr.sbin/dtrace/i386
TESTS_SUBDIRS+= arrays \
		funcs \
		pid \
		ustack

.PATH:		${.CURDIR:H:H:H:H:H}/tests
KYUAFILE=	YES

.include <bsd.test.mk>
