# $FreeBSD: 2952a518c3876ecddade0a292f925f726c906329 $

.PATH: ${SRCTOP}/sys/dev/ata/chipsets

KMOD=	atamicron
SRCS=	ata-micron.c
SRCS+=	ata_if.h bus_if.h device_if.h pci_if.h

.include <bsd.kmod.mk>
