# $FreeBSD: releng/12.2/sys/modules/mlxfw/Makefile 359378 2020-03-27 20:06:40Z kib $
.PATH:  ${SRCTOP}/sys/dev/mlxfw

KMOD=mlxfw
SRCS= \
mlxfw_fsm.c \
mlxfw_mfa2.c \
mlxfw_mfa2_tlv_multi.c
SRCS+=	${LINUXKPI_GENSRCS}

CFLAGS+= \
	-I${SRCTOP}/sys/ofed/include \
	-I${SRCTOP}/sys/compat/linuxkpi/common/include \
	-I${SRCTOP}/sys/contrib/xz-embedded/freebsd \
	-I${SRCTOP}/sys/contrib/xz-embedded/linux/lib/xz

.include <bsd.kmod.mk>
