# $FreeBSD: bcb2ebd44185d40e9114c26b7eef9208a8423ced $

SUBDIR= include

FILESDIR=	${LIBEXECDIR}/bsdconfig/080.console
FILES=		INDEX USAGE

SCRIPTSDIR=	${FILESDIR}
SCRIPTS=	console font keymap repeat saver screenmap ttys

.include <bsd.prog.mk>
