#	@(#)Makefile	8.1 (Berkeley) 5/31/93
#
# $FreeBSD: ed00d012cd375b9a016d2b2e64ead27b5debf63a $

SUBDIR=	fortune strfile datfiles unstr

SUBDIR_DEPEND_datfiles=	strfile

SUBDIR_PARALLEL=

.include <bsd.subdir.mk>
