# $Id: Makefile,v 1.1 2003/09/08 02:27:27 max Exp $
# $FreeBSD: e3ebcd8d725471abb30a204509435ef7ddb39ffa $

PROG=		sdpcontrol
MAN=		sdpcontrol.8
SRCS=		sdpcontrol.c search.c
WARNS?=		2

LIBADD=		bluetooth sdp

.include <bsd.prog.mk>
