# $Id: Makefile,v 1.1 2003/09/08 02:27:27 max Exp $
# $FreeBSD: 8250cd0e91274a457257e466e639e333b4e4fb1d $

PACKAGE=	bluetooth
PROG=		sdpcontrol
MAN=		sdpcontrol.8
SRCS=		sdpcontrol.c search.c
WARNS?=		2

LIBADD=		bluetooth sdp

.include <bsd.prog.mk>
