# $FreeBSD: adf9c0601269d848d04c29ea916abc7dd67c3cc2 $

KYUA_LIB=	drivers
LIBADD=		kyua_model kyua_engine kyua_store

SRCS=	debug_test.cpp		\
	list_tests.cpp		\
	report_junit.cpp	\
	run_tests.cpp		\
	scan_results.cpp

.include <bsd.lib.mk>
