# $FreeBSD: 6c23c8104413a2569dd326dc0161f123b8baa988 $

PACKAGE=	tests

TAP_TESTS_SH=	legacy_test

${PACKAGE}FILES+=		regress.base64.in
${PACKAGE}FILES+=		regress.out
${PACKAGE}FILES+=		regress.sh
${PACKAGE}FILES+=		regress.traditional.in

.include <bsd.test.mk>
