# $FreeBSD: 9e558c044eda95e7dab671d0eec379ed271e107e $

.PATH: ${SRCTOP}/sys/dev/bfe

KMOD=	if_bfe
SRCS=	if_bfe.c miibus_if.h miidevs.h device_if.h bus_if.h pci_if.h opt_platform.h

.include <bsd.kmod.mk>
