# $FreeBSD: f4360de801b209556a2b2bbad26dbaa05f25af39 $

.PATH: ${.PARSEDIR:H:H}/security/mac_veriexec
.PATH: ${.PARSEDIR:H:H}/crypto

KMOD=	mac_veriexec_sha1
SRCS=	mac_veriexec_sha1.c sha1.c

.include <bsd.kmod.mk>

