#	From: @(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: f595be8839c4752efe53ed8accce412842df4375 $

PROG=	talk
SRCS=	ctl.c ctl_transact.c display.c get_addrs.c get_iface.c get_names.c \
	init_disp.c invite.c io.c look_up.c msgs.c talk.c

LIBADD=	ncursesw

.include <bsd.prog.mk>
