/*
 * MD header for contrib/gdtoa
 *
 * $FreeBSD: 2d65061e82a7c1509fc2ca307a1af39266c62933 $
 */

/*
 * NOTE: The definitions in this file must be correct or strtod(3) and
 * floating point formats in printf(3) will break!  The file can be
 * generated by running contrib/gdtoa/arithchk.c on the target
 * architecture.  See contrib/gdtoa/gdtoaimp.h for details.
 */

#define IEEE_8087
#define Arith_Kind_ASL 1
