#	@(#)Makefile	8.1 (Berkeley) 8/14/93
# $FreeBSD: 5606b8fe5a54f1c9319267156308f668e9dd49b8 $

VOLUME=		usd/04.csh
SRCS=		tabs csh.1 csh.2 csh.3 csh.4 csh.a csh.g
MACROS=		-ms
USE_SOELIM=

.include <bsd.doc.mk>
