# $FreeBSD: ac7715d57f5d7bb1f499c28688aa27a4b44d2809 $

TESTSDIR=	${TESTSBASE}/sys/auditpipe

ATF_TESTS_C=	auditpipe_test

TEST_METADATA+= required_user="root"
TEST_METADATA+= required_files="/dev/auditpipe"

.include <bsd.test.mk>
