#	@(#)Makefile	8.2 (Berkeley) 4/28/95
# $FreeBSD: 828900ac02735ae8882a2c5e8199a00d9c6c1474 $

PROG=	cksum
SRCS=	cksum.c crc.c print.c sum1.c sum2.c crc32.c
LINKS=	${BINDIR}/cksum ${BINDIR}/sum
MLINKS=	cksum.1 sum.1

.include <bsd.prog.mk>
