# Makefile for kld char device driver.
# $FreeBSD: ed0b221e5be2965c9ab3f608272593f8a0978523 $

PACKAGE=examples
FILESDIR=${SHAREDIR}/examples/kld/${KMOD}/module
KMOD=	cdev
SRCS=	cdev.c cdevmod.c

.include <bsd.kmod.mk>
