# $FreeBSD: 3fcc4acf4fe1e2b6897ed15fdf4906f2e663ec8d $
# $Whistle: Makefile,v 1.1 1999/12/03 01:44:28 archie Exp $

.PATH: ${SRCTOP}/sys/net

KMOD=	ng_bpf
SRCS=	opt_bpf.h ng_bpf.c bpf_filter.c

.include <bsd.kmod.mk>
