# $FreeBSD: 88eb9220a8cc6476f31e68baabb627cb52f51e66 $

.include <src.opts.mk>

.include "Makefile.common"

PROG_CXX=	zfsd
MAN=		zfsd.8

HAS_TESTS=
SUBDIR.${MK_GOOGLETEST}+= tests

.include <bsd.prog.mk>
