# $FreeBSD: 143ccc988db4c8a230c93ae48ffd51e421002feb $

.PATH: ${SRCTOP}/sys/dev/ste

KMOD=	if_ste
SRCS=	if_ste.c device_if.h bus_if.h pci_if.h
SRCS+=	miibus_if.h opt_platform.h

.include <bsd.kmod.mk>
