# $FreeBSD: 99469ba42243282e203b116898c4543864a8acf0 $

.include <bsd.own.mk>

PACKAGE=	tests

ATF_TESTS_SH+=		cmp_test2
NETBSD_ATF_TESTS_SH=	cmp_test

${PACKAGE}FILES+=	b_flag.out
${PACKAGE}FILES+=	bl_flag.out

.include <netbsd-tests.test.mk>

.include <bsd.test.mk>
