# $FreeBSD: 2ab3a680a4eb40c7b88815160d5804f1cc5e2051 $

SUBDIR= include

FILESDIR=	${LIBEXECDIR}/bsdconfig/020.docsinstall
FILES=		INDEX USAGE

SCRIPTSDIR=	${FILESDIR}
SCRIPTS=	docsinstall

.include <bsd.prog.mk>
