# $FreeBSD: ea8217e66ada6e7396da2b2193ea7edc7d009591 $

.include <src.opts.mk>

LIBXOSRC=	${SRCTOP}/contrib/libxo

.PATH:
.PATH:	${LIBXOSRC}/xolint

SCRIPTS= xolint.pl
MAN=	xolint.1

.include <bsd.prog.mk>
