# $FreeBSD: 9fa2269cb8b264f49a934a0b3ac1640c72d5edb2 $

FILES=          ${SRCTOP}/sys/contrib/dev/wpi/LICENSE
FILESDIR=       ${SHAREDIR}/doc/legal
FILESNAME=	intel_wpi.LICENSE

.include <bsd.prog.mk>

