# $FreeBSD: 158ed4cd945abfd4a968fad24d1c95f6cb9ac0b5 $

.PATH: ${SRCTOP}/sys/dev/sdhci

KMOD=	sdhci
SRCS=	sdhci.c sdhci.h sdhci_if.c sdhci_if.h device_if.h bus_if.h mmcbr_if.h opt_mmccam.h opt_cam.h

.include <bsd.kmod.mk>
