# $FreeBSD: 8eeaa82e68a46038d5068c9bbdb48321a09dc481 $

PACKAGE=	tests

TESTSDIR=	${TESTSBASE}/usr.bin/bmake/execution/joberr

TAP_TESTS_SH=	legacy_test

${PACKAGE}FILES+=	Makefile.test
${PACKAGE}FILES+=	expected.status.1
${PACKAGE}FILES+=	expected.stderr.1
${PACKAGE}FILES+=	expected.stdout.1

.include <bsd.test.mk>
