# $FreeBSD: releng/12.2/sys/modules/dtb/rockchip/Makefile 362244 2020-06-16 20:43:42Z manu $

DTS=	\
	rockchip/rk3399-khadas-edge-captain.dts \
	rockchip/rk3399-khadas-edge.dts \
	rockchip/rk3399-khadas-edge-v.dts \
	rockchip/rk3328-rock64.dts \
	rockchip/rk3399-rockpro64.dts

.include <bsd.dtb.mk>
