#	From: @(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: 1849181a6ef9210e841c75618da1a4fd2195e738 $

.include <src.opts.mk>

PROG=	basename
MLINKS=	basename.1 dirname.1

HAS_TESTS=
SUBDIR.${MK_TESTS}+= tests

.include <bsd.prog.mk>
