# $FreeBSD: releng/12.2/lib/libclang_rt/xray-profiling/Makefile 360545 2020-05-01 20:20:23Z dim $

.include <bsd.init.mk>

LIB=		clang_rt.xray-profiling-${CRTARCH}

SRCS+=		xray/xray_profile_collector.cpp
SRCS+=		xray/xray_profiling.cpp
SRCS+=		xray/xray_profiling_flags.cpp

.include <bsd.lib.mk>
