# $FreeBSD: 286be805ff529b0ef5245bb02f27cbcb05659c2a $

.include <bsd.init.mk>

LIB=		clang_rt.xray-profiling-${CRTARCH}

SRCS+=		xray/xray_profile_collector.cpp
SRCS+=		xray/xray_profiling.cpp
SRCS+=		xray/xray_profiling_flags.cpp

.include <bsd.lib.mk>
