# $FreeBSD: releng/12.2/share/doc/llvm/Makefile 356462 2020-01-07 19:49:10Z dim $

SUBDIR=		clang

SRCDIR=		${SRCTOP}/contrib/llvm-project/llvm

.PATH: ${SRCDIR} ${SRCDIR}/lib/Support

FILESGROUPS=	TOP
TOP=		LICENSE.TXT COPYRIGHT.regex
TOPDIR=		${DOCDIR}/llvm

.include <bsd.prog.mk>
