# $FreeBSD: 35bda425918f63f72217c46ddb1a9e529cbe3528 $

SUBDIR=		clang

SRCDIR=		${SRCTOP}/contrib/llvm-project/llvm

.PATH: ${SRCDIR} ${SRCDIR}/lib/Support

FILESGROUPS=	TOP
TOP=		LICENSE.TXT COPYRIGHT.regex
TOPDIR=		${DOCDIR}/llvm

.include <bsd.prog.mk>
