# $FreeBSD: 1f0f7f95fa684757e892118d1dde1e5b574728e0 $

PACKAGE=	tests

TESTSDIR=	${TESTSBASE}/usr.bin/bmake/basic/t2

TAP_TESTS_SH=	legacy_test

${PACKAGE}FILES+=	Makefile.test
${PACKAGE}FILES+=	expected.status.1
${PACKAGE}FILES+=	expected.stderr.1
${PACKAGE}FILES+=	expected.stdout.1

.include <bsd.test.mk>
