# $FreeBSD: releng/12.2/usr.bin/clang/llvm-profdata/Makefile 356462 2020-01-07 19:49:10Z dim $

PROG_CXX=	llvm-profdata

SRCDIR=		llvm/tools/llvm-profdata
SRCS+=		llvm-profdata.cpp

LIBADD+=	z

.include "../llvm.prog.mk"
