# $FreeBSD: 165d6c9edd3f1628bb2589fe1df59edeffcddfaf $

.PATH: ${SRCTOP}/sys/dev/mvs

KMOD=	mvs
SRCS=	mvs.c mvs_pci.c mvs.h mvs_if.c mvs_if.h device_if.h bus_if.h pci_if.h opt_cam.h

.include <bsd.kmod.mk>
