# $FreeBSD: releng/12.2/stand/efi/gptboot/Makefile 348812 2019-06-08 19:02:17Z imp $

# ZFS is not supported, we want debugging until this is vetted and
# we don't want the gptboot.efifat thing created.
MK_LOADER_ZFS=no
EFI_DEBUG=yes
NOFAT=yes

BOOT1?=		gptboot
.PATH:		${SRCTOP}/stand/efi/boot1 ${SRCTOP}/stand/libsa
CFLAGS+=	-I${SRCTOP}/stand/efi/boot1
CFLAGS+=	-I${.CURDIR}
CFLAGS+=	-DBOOTPROG=\"gptboot.efi\"
SRCS+=		gpt.c
CWARNFLAGS.gpt.c+=	-Wno-sign-compare -Wno-cast-align
WARNS=6
.include "${.CURDIR}/../boot1/Makefile"
