# $FreeBSD: 884b991721d12710d6839c855215eeb3846c053a $

PACKAGE=	tests

TESTSDIR=	${TESTSBASE}/usr.bin/bmake/execution/plus

TAP_TESTS_SH=	legacy_test

${PACKAGE}FILES+=	Makefile.test
${PACKAGE}FILES+=	expected.status.1
${PACKAGE}FILES+=	expected.stderr.1
${PACKAGE}FILES+=	expected.stdout.1

.include <bsd.test.mk>
