# $FreeBSD: 4f211ad5335759101fa3a5406029641f536a8186 $
# All the dts files for Freescale (now NXP) systems we support.
DTS=	freescale/fsl-lx2160a-clearfog-cx.dts \
	freescale/fsl-lx2160a-honeycomb.dts \
	freescale/fsl-lx2160a-qds.dts \
	freescale/fsl-lx2160a-rdb.dts

.include <bsd.dtb.mk>
