# $FreeBSD: cba5cee47ea9025ef620ff77ac7e59e525d5f94b $
# Author: Shteryana Shopova <syrinx@FreeBSD.org>

SUBDIR=	libbsnmptools \
	bsnmptools

SUBDIR_DEPEND_bsnmptools=	libbsnmptools

SUBDIR_PARALLEL=

.include <bsd.subdir.mk>
