#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: 983392b7a1e0575a30addfde50489026d52e1efe $

PROG=	finger
SRCS=	finger.c lprint.c net.c sprint.c util.c
MAN=	finger.1 finger.conf.5

.include <bsd.prog.mk>
