# $FreeBSD: releng/12.2/lib/libclang_rt/stats_client/Makefile 360545 2020-05-01 20:20:23Z dim $

.include <bsd.init.mk>

LIB=		clang_rt.stats_client-${CRTARCH}

SRCS+=		stats/stats_client.cpp

.include <bsd.lib.mk>
