# $FreeBSD: fa4499c9d11bd87b09799ddb8f1c6736a10c1564 $

.include <bsd.own.mk>

NETBSD_ATF_TESTS_C+=	inet_addr_test
NETBSD_ATF_TESTS_C+=	inet_network_test

.include "../Makefile.netbsd-tests"

.include <bsd.test.mk>
