# $FreeBSD: releng/12.2/usr.bin/clang/llvm-extract/Makefile 356462 2020-01-07 19:49:10Z dim $

PROG_CXX=	llvm-extract

SRCDIR=		llvm/tools/llvm-extract
SRCS+=		llvm-extract.cpp

LIBADD+=	z

.include "../llvm.prog.mk"
