# $FreeBSD: b920eb14bc154c6ec8d59a0b1fe83ee0d2bb59bf $
# $NetBSD: Makefile,v 1.6 2009/04/14 22:15:21 lukem Exp $

.include <bsd.own.mk>

PROG=	iconv
#SRCS=	iconv.c
MAN=	iconv.1

.include <bsd.prog.mk>
