# $FreeBSD: e0b2452afdd03dde8257cca9d710cd88122b89e2 $

CONFS=		iwmbtfw.conf
CONFSDIR=       /etc/devd
PROG=		iwmbtfw
MAN=		iwmbtfw.8
LIBADD+=	usb
SRCS=		main.c iwmbt_fw.c iwmbt_hw.c

.include <bsd.prog.mk>
