# $FreeBSD: b4bdb25aac525f169ccbb1e25b93a901c98269e8 $

PACKAGE=	tests

TESTSDIR=	${TESTSBASE}/usr.bin/bmake/basic/t1

TAP_TESTS_SH=	legacy_test

${PACKAGE}FILES+=		Makefile.test
${PACKAGE}FILES+=		expected.status.1
${PACKAGE}FILES+=		expected.stderr.1
${PACKAGE}FILES+=		expected.stdout.1

.include <bsd.test.mk>
