# $FreeBSD: 0ece6d2974170b5cd03ccf9e0bc5b28c116bbdaf $ 

INCS=	_ctype.h _inttypes.h _langinfo.h _locale.h _monetary.h _stdio.h\
	_stdlib.h _string.h _strings.h _time.h _uchar.h _wchar.h
INCSDIR=${INCLUDEDIR}/xlocale

.include <bsd.prog.mk>
