# $FreeBSD: ebf33455b9b840a3efa83f14947d2a83e154cc46 $

PACKAGE=runtime
CONFS=	minfree
VAR_CRASH=	/var/crash
VAR_CRASH_MODE=	0750
CONFSDIR=	VAR_CRASH
PROG=	savecore
LIBADD=	z xo
MAN=	savecore.8

.include <bsd.prog.mk>
