# $FreeBSD: 64a2ef8079e82372411fb428dcf2dbd9d57b419b $

.include <src.opts.mk>

FILESDIR=	${SHAREDIR}/doc/ntp/drivers/scripts

.if ${MK_HTML} != "no"
FILES=	footer.txt style.css
.endif

.PATH: ${SRCTOP}/contrib/ntp/html/drivers/scripts

.include <bsd.prog.mk>
