# $FreeBSD: 1398fa8c5484724948805e35bb04f24aa63f452e $

.PATH:  ${SRCTOP}/sys/dev/amdsbwd
KMOD    = amdsbwd
SRCS    = amdsbwd.c
SRCS    += device_if.h bus_if.h pci_if.h isa_if.h opt_amdsbwd.h

.include <bsd.kmod.mk>
