# $FreeBSD: fbc1fa0c2154e57d903e1489222636d72c20971a $

.PATH:		${SRCTOP}/sys/dev/intpm
KMOD		= intpm
SRCS		= device_if.h bus_if.h iicbus_if.h smbus_if.h pci_if.h \
		  opt_intpm.h intpmreg.h intpm.c

.include <bsd.kmod.mk>
