# $FreeBSD: eae22ec84e0c5743faf028c21463d00c80449f0a $

PACKAGE=	tests

TESTSDIR=	${TESTSBASE}/usr.bin/bmake/syntax/funny-targets

TAP_TESTS_SH=	legacy_test

${PACKAGE}FILES+=		Makefile.test
${PACKAGE}FILES+=		expected.status.1
${PACKAGE}FILES+=		expected.status.2
${PACKAGE}FILES+=		expected.stderr.1
${PACKAGE}FILES+=		expected.stderr.2
${PACKAGE}FILES+=		expected.stdout.1
${PACKAGE}FILES+=		expected.stdout.2

.include <bsd.test.mk>
