# $FreeBSD: 064ab3a9435f435444b1681244b60fb90a354497 $
#
# PR bin/6612 / GRN r102178
#

test1: colons::colons::target

colons::colons::target:
	@echo '${.TARGET}'

test2: exclamation!target

exclamation!target:
	@echo '${.TARGET}
