# $Id: Makefile,v 1.7 2003/09/07 18:15:55 max Exp $
# $FreeBSD: fc3932566d40a9085556509ba37a87b09574c755 $

PACKAGE=	bluetooth
PROG=		rfcomm_sppd
SRCS=		rfcomm_sppd.c rfcomm_sdp.c
WARNS?=		2

LIBADD=		bluetooth sdp util

.include <bsd.prog.mk>
