# $Id: Makefile,v 1.7 2003/09/07 18:15:55 max Exp $
# $FreeBSD: b17c5cfe4f372bf8aa9a628d58b4a4d34cf3b838 $

PROG=		rfcomm_sppd
SRCS=		rfcomm_sppd.c rfcomm_sdp.c
WARNS?=		2

LIBADD=		bluetooth sdp util

.include <bsd.prog.mk>
