#! /bin/sh
#
# Common setup.
#
# $FreeBSD: a8816a2cf1905d6f9acf04d6f1ec0dc6bb4c73cd $
#
PATH=../:.:$PATH
. config
. config.mesh

WLAN=`ifconfig wlan create wlanmode mesh wlandev $WIRELESS`
ifconfig $WLAN meshid $MESHID channel $CHANNEL mtu 1500
wlandebug -i $WLAN mesh+hwmp+state+scan+assoc
