#
# Default caching daemon configuration file
# $FreeBSD: 19a8b5b9545235e51e43e2a12a20398ba1e0a32d $
#

enable-cache passwd yes
enable-cache group yes
enable-cache hosts yes
enable-cache services yes
enable-cache protocols yes
enable-cache rpc yes
enable-cache networks yes
