# $FreeBSD: releng/12.2/usr.bin/clang/llvm-rtdyld/Makefile 356462 2020-01-07 19:49:10Z dim $

PROG_CXX=	llvm-rtdyld
MAN=

SRCDIR=		llvm/tools/llvm-rtdyld
SRCS+=		llvm-rtdyld.cpp

LIBADD+=	z

.include "../llvm.prog.mk"
