# $FreeBSD: cc4d160a9b99e6ee88e75636e17068e14ff0db73 $

.include <bsd.init.mk>

LIB=		clang_rt.asan_static-${CRTARCH}

SRCS+=		asan/asan_rtl_static.cpp
SRCS+=		asan/asan_rtl_x86_64.S

.include <bsd.lib.mk>
