# $FreeBSD: 82e2a697df6ba6026d1568d72756b94f82332d66 $
# Module for Alteon Networks Tigon PCI gigabit ethernet driver for FreeBSD.
# Modules for Texas Instruments ARM SoCs are located in sys/modules/arm_ti.

.PATH: ${SRCTOP}/sys/dev/ti

KMOD=	if_ti
SRCS=	if_ti.c device_if.h bus_if.h pci_if.h opt_ti.h

.include <bsd.kmod.mk>
