# $FreeBSD: releng/12.2/sys/modules/ice_ddp/Makefile 365733 2020-09-14 22:42:17Z erj $

KMOD=	ice_ddp
FIRMWS=	${SRCTOP}/sys/contrib/dev/ice/ice-1.3.16.0.pkg:ice_ddp:0x01031000

.include <bsd.kmod.mk>
