# $FreeBSD: e8ec319a0ae4f3d2c32f6bf7647b8b6d873ccda3 $

FILESDIR=	${SHAREDIR}/bsdconfig/media
FILES=		any.subr cdrom.subr common.subr directory.subr dos.subr \
		floppy.subr ftp.subr http.subr httpproxy.subr network.subr \
		nfs.subr options.subr tcpip.subr ufs.subr usb.subr wlan.subr

.include <bsd.prog.mk>
