#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: 15ffee09816017db9b5a1582d3e8a7f877854e87 $

.include <src.opts.mk>

PROG=	pr
SRCS=	pr.c egetopt.c

HAS_TESTS=
SUBDIR.${MK_TESTS}+= tests

.include <bsd.prog.mk>
