# $FreeBSD: 35e66c3e17e6254068f7675fd4fd1ec7dd1b6304 $

.PATH:		${.CURDIR}/../../../dev/jedec_dimm
KMOD		= jedec_dimm
SRCS		= jedec_dimm.c jedec_dimm.h bus_if.h device_if.h smbus_if.h

.include <bsd.kmod.mk>
