# $FreeBSD: releng/12.2/share/doc/llvm/clang/Makefile 356462 2020-01-07 19:49:10Z dim $

SRCDIR=		${SRCTOP}/contrib/llvm-project/clang

.PATH: ${SRCDIR}

FILESGROUPS=	TOP
TOP=		LICENSE.TXT
TOPDIR=		${DOCDIR}/llvm/clang

.include <bsd.prog.mk>
