# $FreeBSD: 4183264a0dc7eea180dd36ec23a5f2a137ee542d $

SRCDIR=		${SRCTOP}/contrib/llvm-project/clang

.PATH: ${SRCDIR}

FILESGROUPS=	TOP
TOP=		LICENSE.TXT
TOPDIR=		${DOCDIR}/llvm/clang

.include <bsd.prog.mk>
