# $FreeBSD: d3532f01b7b6e7c59ba8ccb578c783213cc80c14 $

ATF_TESTS_C+=	sbuf_core_test
ATF_TESTS_C+=	sbuf_stdio_test
ATF_TESTS_C+=	sbuf_string_test

LIBADD+=	sbuf util

WARNS?=		6

.include <bsd.test.mk>
