# $FreeBSD: 77ac03c3f14b18c1efdb03538481dd219eb0427f $

.include <src.opts.mk>

INCS=	ftp.h inet.h nameser.h nameser_compat.h tftp.h
INCS+=	telnet.h
INCSDIR=${INCLUDEDIR}/arpa

.include <bsd.prog.mk>
