# $FreeBSD: b2a93b3af6d659d2c87b5aa1c70ece9ca9a02680 $

SHLIB_NAME=	dynthr_mod.so
SHLIBDIR=	${TESTSDIR}
SRCS=		dynthr_mod.c
LIBADD=		pthread

TESTSDIR:=	${TESTSBASE}/${RELDIR:C/libc\/tests/libc/:H}


.include <bsd.lib.mk>
