# $FreeBSD: releng/12.2/usr.bin/clang/llvm-strings/Makefile 363494 2020-07-24 20:48:06Z dim $

PROG_CXX=	llvm-strings

SRCDIR=		llvm/tools/llvm-strings
SRCS+=		llvm-strings.cpp

.include "../llvm.prog.mk"
