# $FreeBSD: 3701b14518727f1339511c4d6b34ce65284b014e $

.PATH: ${SRCTOP}/sys/dev/sym

KMOD=	sym
SRCS=	sym_hipd.c opt_sym.h opt_cam.h opt_scsi.h
SRCS+=	device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>
