# $FreeBSD: a81a965bebb9699733b746397d5da80512e538ea $
# included by geom_sched children

.PATH: ${SRCTOP}/sys/geom/sched

# 6.x needs this path
#CFLAGS += -I${SRCTOP}/sys/geom/sched

# .include <bsd.kmod.mk>
