# $FreeBSD: 746c19686768654910aaece46fc0ea23e44649ac $

SUBDIR= beastie \
	blank \
	daemon \
	dragon \
	fade \
	fire \
	green \
	logo \
	plasma \
	rain \
	snake \
	star \
	warp

.include <bsd.subdir.mk>
