# $FreeBSD: e3008fad6fe1d55453a4db19a3e8fb8aa49f26da $

PACKAGE=	tests

TESTSDIR=	${TESTSBASE}/usr.bin/bmake/execution/ellipsis

TAP_TESTS_SH=	legacy_test

${PACKAGE}FILES+=		Makefile.test
${PACKAGE}FILES+=		expected.status.1
${PACKAGE}FILES+=		expected.stderr.1
${PACKAGE}FILES+=		expected.stdout.1

.include <bsd.test.mk>
