# $FreeBSD: fb76fec9119611afe21d6e4740c57b5382fa9495 $

FILES=	README pc-autoinstall.conf pcinstall.cfg.fbsd-netinstall \
	pcinstall.cfg.geli pcinstall.cfg.gmirror pcinstall.cfg.netinstall \
	pcinstall.cfg.restore pcinstall.cfg.rsync pcinstall.cfg.upgrade \
	pcinstall.cfg.zfs

FILESDIR=${SHAREDIR}/examples/pc-sysinstall

.include <bsd.prog.mk>
