# $FreeBSD: c092b18169b5abef3ee77c6c1f70765f57b94e73 $

.PATH: ${SRCTOP}/sys/dev/ffec

KMOD=	if_ffec
SRCS=	if_ffec.c miibus_if.h device_if.h bus_if.h pci_if.h ofw_bus_if.h opt_global.h

.include <bsd.kmod.mk>
