# $FreeBSD: e0ed6f40c4c7283ac4b080c9d2905c649701f3e1 $

.PATH: ${.CURDIR}/../../security/mac_veriexec
.PATH: ${.CURDIR}/../../crypto/sha2

KMOD=	mac_veriexec_sha512
SRCS=	mac_veriexec_sha512.c sha512c.c

.include <bsd.kmod.mk>

