# $FreeBSD: releng/12.2/usr.bin/clang/llvm-bcanalyzer/Makefile 356462 2020-01-07 19:49:10Z dim $

PROG_CXX=	llvm-bcanalyzer

SRCDIR=		llvm/tools/llvm-bcanalyzer
SRCS+=		llvm-bcanalyzer.cpp

.include "../llvm.prog.mk"
