# $FreeBSD: ddc75296ad64e4b37b3eda483052435fb437823d $

.PATH: ${SRCTOP}/sys/dev/ata/chipsets

KMOD=	atajmicron
SRCS=	ata-jmicron.c
SRCS+=	ata_if.h bus_if.h device_if.h pci_if.h

.include <bsd.kmod.mk>
