# $FreeBSD: 71efd2e755c15bdc510660a2f1a4269dd0665b3f $

.PATH: ${SRCTOP}/sys/dev/intel
KMOD=   pchtherm
SRCS=   pchtherm.c
SRCS+=  device_if.h bus_if.h pci_if.h opt_platform.h

.include <bsd.kmod.mk>
