# $FreeBSD: releng/12.2/sys/modules/rockchip/Makefile 358648 2020-03-04 21:20:15Z manu $
# Build modules specific to RockChip.

SUBDIR = \
	rk_i2c \
	rk805 \
	rk_dwmmc \
	rk_spi

.include <bsd.subdir.mk>
