# $FreeBSD: 39ccd333bedfad410adbf845d4dc9e6debb24317 $

TESTSDIR=	${TESTSBASE}/cddl/usr.sbin/dtrace/amd64
TESTS_SUBDIRS+= arrays

.PATH:		${.CURDIR:H:H:H:H:H}/tests
KYUAFILE=	YES

.include <bsd.test.mk>
