#
# $FreeBSD: f0a5c2f1daa2ffd84b7e7386cea22c053fa6ad91 $
#

.PATH: ${SRCTOP}/sys/tests/callout_test

KMOD=	callout_test
SRCS=	callout_test.c

#
# Enable full debugging
#
#CFLAGS += -g

.include <bsd.kmod.mk>
