#
# $FreeBSD: 8623e01a3ea98c9bc78bc1369f6bf9d43fc10f71 $
#

.PATH: ${SRCTOP}/sys/tests/framework

KMOD=	kern_testfrwk
SRCS=	kern_testfrwk.c
SRCS+=	bus_if.h device_if.h

#
# Enable full debugging
#
#CFLAGS += -g

.include <bsd.kmod.mk>
