# $FreeBSD: dfbe0aeddc4756b5a238a7d1a4419c08373257a7 $

PACKAGE=runtime
.PATH: ${.CURDIR:H:H}/misc ${SRCTOP}/sys/geom/virstor

GEOM_CLASS=	virstor

SRCS+=	binstream.c
SRCS+=	g_virstor_md.c

.include <bsd.lib.mk>
