# $FreeBSD: 24b4e508af18e341b86416733d2c66d3ad30a85d $

PACKAGE=geom
.PATH: ${.CURDIR:H:H}/misc ${SRCTOP}/sys/geom/virstor

GEOM_CLASS=	virstor

SRCS+=	binstream.c
SRCS+=	g_virstor_md.c

.include <bsd.lib.mk>
