# $FreeBSD: 4e4ef2e694617d84df41e4d9d69cd4ee7618c47b $

.PATH: ${SRCTOP}/cddl/compat/opensolaris/lib/libumem

PACKAGE=	zfs
LIB=	umem
SRCS=	umem.c
WARNS?=	3
CFLAGS+= -I${SRCTOP}/cddl/compat/opensolaris/lib/libumem

.include <bsd.lib.mk>
