# $FreeBSD: 39ed62f1cc4ebca9492c86e1a0b269b50035771c $

.PATH: ${SRCTOP}/cddl/compat/opensolaris/lib/libumem

LIB=	umem
SRCS=	umem.c
WARNS?=	3
CFLAGS+= -I${SRCTOP}/cddl/compat/opensolaris/lib/libumem

.include <bsd.lib.mk>
