# $FreeBSD: f78fa64968fded495e85443f82534db78f5a680a $

PROG=	rpcgen
SRCS=	rpc_main.c  rpc_clntout.c rpc_cout.c rpc_hout.c rpc_parse.c \
	rpc_sample.c rpc_scan.c rpc_svcout.c rpc_tblout.c rpc_util.c

.include <bsd.prog.mk>
