# $FreeBSD: b45985177f8301222dcf4f214b69a0cabc6a8f1f $

.include <src.opts.mk>

SUBDIR+=		gtest
SUBDIR+=		.WAIT
SUBDIR+=		gmock
SUBDIR+=		.WAIT
SUBDIR+=		gmock_main
SUBDIR+=		gtest_main

SUBDIR.${MK_TESTS}+=	tests

.include <bsd.subdir.mk>
