# $FreeBSD: 7ab56ee5e6d5baa1a7358b09f76e1ee38694c378 $

.PATH:	${SRCTOP}/sys/dev/nctgpio
KMOD=	nctgpio
SRCS=	nctgpio.c
SRCS+=	device_if.h bus_if.h isa_if.h gpio_if.h opt_platform.h

.include <bsd.kmod.mk>
