# $FreeBSD: 2f0545a6008b74def048198b721f71928b21d543 $

.PATH:  ${SRCTOP}/sys/dev/ntb/ntb_hw

KMOD    = ntb_hw_amd
SRCS    = ntb_hw_amd.c
SRCS += device_if.h bus_if.h pci_if.h ntb_if.h

.include <bsd.kmod.mk>
