# $FreeBSD: be6eb0df6e0309db7e6fc26e6117ddd6fbae9c2b $

SUBDIR=	rtwnrtl8188eu rtwnrtl8192cT rtwnrtl8192cU rtwnrtl8192eu rtwnrtl8812au \
	rtwnrtl8821au rtwnrtl8192cE rtwnrtl8192cEB rtwnrtl8188ee

.include <bsd.subdir.mk>
