# $FreeBSD: 6b0e53fa0865f4933bc2ca4af16ac888369b73ca $

TESTSDIR=	${TESTSBASE}/sys/capsicum

ATF_TESTS_C+=	bindat_connectat
ATF_TESTS_C+=	ioctls_test

CFLAGS+=	-I${SRCTOP}/tests

WARNS?=	6

.include <bsd.test.mk>
