# $FreeBSD: releng/12.2/tests/sys/capsicum/Makefile 356768 2020-01-15 21:05:43Z emaste $

TESTSDIR=	${TESTSBASE}/sys/capsicum

ATF_TESTS_C+=	bindat_connectat
ATF_TESTS_C+=	ioctls_test

CFLAGS+=	-I${SRCTOP}/tests

WARNS?=	6

.include <bsd.test.mk>
