# $FreeBSD: 5873c0758a9a533efeddcb6ebc2d3d8e16a2adfa $

SUBDIR=	common_source .WAIT \
	chkprintcap lp lpc lpd lpq lpr lprm lptest pac \
	filters filters.ru
SUBDIR_PARALLEL=

# Questions/ideas for lpr & friends could also be sent to:
#	freebsd-print@bostonradio.org

.include <bsd.subdir.mk>
