# $FreeBSD: releng/12.2/lib/libedit/readline/Makefile 352275 2019-09-13 06:50:02Z bapt $

.PATH: ${SRCTOP}/contrib/libedit/readline
INCS=	readline.h history.h tilde.h

INCSDIR= ${INCLUDEDIR}/edit/readline

.include <bsd.lib.mk>
