# $FreeBSD: 7fecfd327e5029356895054d7a27733b5d17c87d $

PACKAGE=	tests

TESTSDIR=	${TESTSBASE}/usr.bin/bmake/shell/path_select

TAP_TESTS_SH=	legacy_test

${PACKAGE}FILES+=		Makefile.test
${PACKAGE}FILES+=		expected.status.1
${PACKAGE}FILES+=		expected.status.2
${PACKAGE}FILES+=		expected.stderr.1
${PACKAGE}FILES+=		expected.stderr.2
${PACKAGE}FILES+=		expected.stdout.1
${PACKAGE}FILES+=		expected.stdout.2
${PACKAGE}FILES+=		shell

.include <bsd.test.mk>
