# $FreeBSD: 817c5ba68777344b1a860528711209f6df4690a9 $

.PATH:		${SRCTOP}/sys/dev/cyapa
KMOD		= cyapa
SRCS		= cyapa.c device_if.h bus_if.h iicbus_if.h vnode_if.h \
		  opt_evdev.h

.include <bsd.kmod.mk>
