# $FreeBSD: 3a9e64adb10f22f6884ce4e166a9f0bc928ba59c $

SUBDIR=	lib \
	.WAIT \
	svn \
	svnadmin \
	svnbench \
	svndumpfilter \
	svnfsfs \
	svnlook \
	svnserve \
	svnsync \
	svnversion \
	svnmucc \
	svnrdump
SUBDIR_PARALLEL=

.include <bsd.subdir.mk>
