# $FreeBSD: releng/12.2/usr.bin/svn/Makefile 362180 2020-06-14 17:36:43Z dim $

SUBDIR=	lib \
	.WAIT \
	svn \
	svnadmin \
	svnbench \
	svndumpfilter \
	svnfsfs \
	svnlook \
	svnserve \
	svnsync \
	svnversion \
	svnmucc \
	svnrdump
SUBDIR_PARALLEL=

.include <bsd.subdir.mk>
