# $FreeBSD: d4a0b91587e7dcbc7b56a967c5a5b9aafca6d6f1 $

KYUA_LIB=	model
LIBADD=		lutok

SRCS=	context.cpp		\
	exceptions.cpp		\
	metadata.cpp		\
	test_case.cpp		\
	test_program.cpp	\
	test_result.cpp

.include <bsd.lib.mk>
