# $FreeBSD: 3d5ec770799dea50a11eef4f8eb0c227a3315a07 $

.PATH:	${SRCTOP}/sys/dev/acpi_support

KMOD=	acpi_asus
SRCS=	acpi_asus.c opt_acpi.h acpi_if.h bus_if.h device_if.h
SRCS+= opt_ddb.h

.include <bsd.kmod.mk>
