#	From: @(#)Makefile	8.2 (Berkeley) 2/28/94
# $FreeBSD: e92eeab264a228ed27961a71e29d1c38657b506f $

VOLUME=		smm/08.sendmailop
SRCS=		op.me
MACROS=		-me
USE_PIC=
USE_EQN=
SRCDIR=		${SRCTOP}/contrib/sendmail/doc/op

.include <bsd.doc.mk>
