# $FreeBSD: 50ae28dc736d1a3eadd9d3dc451ac9d21dacb5d9 $
# $NetBSD: Makefile.inc,v 1.2 2008/10/25 22:35:36 apb Exp $

CODE=	MAC
ESUBDIR= APPLE
TABLENAME= %%PART%%%UCS
RTABLENAME= UCS%%%PART%%
ENCID=	%%PART%%

.include "../Makefile.part"
