# $FreeBSD: 3a7703a2d294053d17506d7439e35044a056ff89 $

FILES=	functions-bsdlabel.sh functions-cleanup.sh functions-disk.sh \
	functions-extractimage.sh functions-ftp.sh functions-installcomponents.sh \
	functions-installpackages.sh functions-localize.sh functions-mountdisk.sh \
	functions-mountoptical.sh functions-networking.sh \
	functions-newfs.sh functions-packages.sh functions-parse.sh \
	functions-runcommands.sh functions-unmount.sh \
	functions-upgrade.sh functions-users.sh \
	functions.sh parseconfig.sh startautoinstall.sh installimage.sh
FILESMODE=	${BINMODE}
FILESDIR=${SHAREDIR}/pc-sysinstall/backend

.include <bsd.prog.mk>
