# $FreeBSD: 29cd2d05b54624691ac28eea153ad710dcdc3055 $

.PATH:		${SRCTOP}/sys/dev/iicbus
KMOD		= nxprtc
SRCS		= nxprtc.c bus_if.h clock_if.h device_if.h iicbus_if.h ofw_bus_if.h opt_platform.h

.include <bsd.kmod.mk>
