# $FreeBSD: 97fa52b60520676df2ba95d71b6d9dc53fd5e866 $

SUBDIR= include

FILESDIR=	${LIBEXECDIR}/bsdconfig/110.mouse
FILES=		INDEX USAGE

SCRIPTSDIR=	${FILESDIR}
SCRIPTS=	disable enable flags mouse port type

.include <bsd.prog.mk>
