# $FreeBSD: d660e452a65980d9c17501dd896182e5c2cae437 $

SUBDIR= include share

FILESDIR=	${LIBEXECDIR}/bsdconfig/040.password
FILES=		INDEX USAGE

SCRIPTSDIR=	${FILESDIR}
SCRIPTS=	password

.include <bsd.prog.mk>
