#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: c38dae383ddd3ceb907ae10e90a5be471656c683 $

.include <src.opts.mk>

PROG=	unifdef
SCRIPTS=unifdefall.sh
MLINKS=	unifdef.1 unifdefall.1

HAS_TESTS=
SUBDIR.${MK_TESTS}+= tests

.include <bsd.prog.mk>
