# $FreeBSD: releng/12.2/tests/sys/vm/Makefile 353148 2019-10-06 20:36:25Z jilles $

PACKAGE=	tests

TESTSDIR=	${TESTSBASE}/sys/vm

ATF_TESTS_C+=	mlock_test \
		mmap_test \
		page_fault_signal

.include <bsd.test.mk>
