 # $FreeBSD: 3b51f87b2827ea5e5b267d9545089c647cf00736 $

.PATH: ${SRCTOP}/sys/dev/exca

KMOD=	exca
SRCS=	exca.c device_if.h bus_if.h power_if.h card_if.h pccarddevs.h

EXPORT_SYMS=	YES

.include <bsd.kmod.mk>
