# $FreeBSD: releng/12.2/usr.bin/clang/llvm-dwp/Makefile 362719 2020-06-28 07:43:43Z dim $

PROG_CXX=	llvm-dwp
MAN=

SRCDIR=		llvm/tools/llvm-dwp
SRCS+=		DWPError.cpp
SRCS+=		llvm-dwp.cpp

LIBADD+=	z

.include "../llvm.prog.mk"
