# $FreeBSD: 7e44778bc165f71f350b2a03b9ccf667b7b30449 $

.PATH: ${SRCTOP}/sys/dev/ata/chipsets

KMOD=	atasiliconimage
SRCS=	ata-siliconimage.c
SRCS+=	ata_if.h bus_if.h device_if.h pci_if.h

.include <bsd.kmod.mk>
