# $FreeBSD: de6e57c37466c62cd6ecf356efb93b8ba3e7188e $

.PATH: ${SRCTOP}/sys/arm/ti/cpsw

KMOD=   if_cpsw
SRCS=   if_cpsw.c device_if.h bus_if.h ofw_bus_if.h miibus_if.h syscon_if.h

.include <bsd.kmod.mk>
