# $FreeBSD: 1695c881d3adc2a7c5c44efe45540470ad0c97c7 $

PACKAGE=	tests

TESTSDIR=	${TESTSBASE}/usr.bin/bmake/shell/select

TAP_TESTS_SH=	legacy_test

${PACKAGE}FILES+=		Makefile.test
${PACKAGE}FILES+=		expected.status.1
${PACKAGE}FILES+=		expected.status.2
${PACKAGE}FILES+=		expected.stderr.1
${PACKAGE}FILES+=		expected.stderr.2
${PACKAGE}FILES+=		expected.stdout.1
${PACKAGE}FILES+=		expected.stdout.2

.include <bsd.test.mk>
