#!/bin/sh
#
# $FreeBSD: releng/11.3/release/amd64/amd64.conf 326015 2017-11-20 15:57:11Z gjb $
#

# Configuration file for release/release.sh to build amd64/amd64.

TARGET="amd64"
TARGET_ARCH="amd64"
KERNEL="GENERIC"
