# $FreeBSD: 7f622b293f12b81550afd744dbf9deb7a2034b3f $

.PATH: ${.CURDIR}/../../security/mac_veriexec
.PATH: ${.CURDIR}/../../crypto/sha2

KMOD=	mac_veriexec_sha384
SRCS=	mac_veriexec_sha384.c sha512c.c

.include <bsd.kmod.mk>

