/* $FreeBSD: 36418d30fedf4b135cca3d1a749e8f53677c78e6 $ */

/* #undef HAVE_SYS_BYTEORDER_H */
/* #undef HAVE_AVAILABILITY_MACROS_H */
/* #undef HAVE_TARGET_CONDITIONALS_H */
/* #undef HAVE_LIBKERN_OSATOMIC_H */

#define HAVE_SYSCONF 1

/* #undef HAVE_OSATOMIC_COMPARE_AND_SWAP_INT */
/* #undef HAVE_OSATOMIC_COMPARE_AND_SWAP_LONG */

#define HAVE_SYNC_BOOL_COMPARE_AND_SWAP_INT 1
#define HAVE_SYNC_BOOL_COMPARE_AND_SWAP_LONG 1
