# $FreeBSD: 35fe0dfef0dd7a441501bea48d89f150a2004a37 $
# Build modules specific to Allwinner.

SUBDIR = \
	aw_mmc \
	aw_pwm \
	aw_rtc \
	aw_rsb \
	aw_sid \
	aw_spi \
	aw_thermal \
	axp81x \
	if_awg

.include <bsd.subdir.mk>
