# $FreeBSD: releng/12.2/sys/modules/allwinner/Makefile 362401 2020-06-19 18:10:39Z manu $
# Build modules specific to Allwinner.

SUBDIR = \
	aw_mmc \
	aw_pwm \
	aw_rtc \
	aw_rsb \
	aw_sid \
	aw_spi \
	aw_thermal \
	axp81x \
	if_awg

.include <bsd.subdir.mk>
