#	from: @(#)Makefile	8.1 (Berkeley) 6/4/93
# $FreeBSD: a65d1d7da981e68e62746dc3ff921400ff11e750 $

CONFS=	gettytab
PROG=	getty
SRCS=	main.c init.c subr.c chat.c
LIBADD=	util
MAN=	gettytab.5 ttys.5 getty.8

WFORMAT=0

.include <bsd.prog.mk>

