#	from: @(#)Makefile	8.1 (Berkeley) 6/4/93
# $FreeBSD: 0296e455f3988348be08d9224280435572d042ca $

PACKAGE=	runtime

CONFS=	gettytab
PROG=	getty
SRCS=	main.c init.c subr.c chat.c
LIBADD=	util
MAN=	gettytab.5 ttys.5 getty.8

WFORMAT=0

.include <bsd.prog.mk>

