# $FreeBSD: releng/12.2/lib/libclang_rt/xray-fdr/Makefile 360545 2020-05-01 20:20:23Z dim $

.include <bsd.init.mk>

LIB=		clang_rt.xray-fdr-${CRTARCH}

SRCS+=		xray/xray_fdr_flags.cpp
SRCS+=		xray/xray_fdr_logging.cpp

.include <bsd.lib.mk>
