# $Id: Makefile,v 1.7 2003/08/14 20:07:14 max Exp $
# $FreeBSD: 36ef850fc6d882fc5b47d4b29f64decff2062dc3 $

PROG=		btsockstat
WARNS?=		2
BINGRP=		kmem
BINMODE=	2555

LIBADD=		bluetooth kvm

.include <bsd.prog.mk>
