# $Id: Makefile,v 1.7 2003/08/14 20:07:14 max Exp $
# $FreeBSD: 33e101fd0e5184d89f8142ce3b2368e3bc4f1e82 $

PACKAGE=	bluetooth
PROG=		btsockstat
WARNS?=		2
BINGRP=		kmem
BINMODE=	2555

LIBADD=		bluetooth kvm

.include <bsd.prog.mk>
