# $FreeBSD: af17a273ad8fdcd22c90e9a376b5dc33936852ac $

PACKAGE=	tests

TAP_TESTS_SH=	legacy_test

${PACKAGE}FILES+=		regress.00.in
${PACKAGE}FILES+=		regress.00.out
${PACKAGE}FILES+=		regress.01.out
${PACKAGE}FILES+=		regress.01.sh
${PACKAGE}FILES+=		regress.sh

.include <bsd.test.mk>
