# $FreeBSD: 584783ddffe2a32b9b7a5af822679b8aa4df7e76 $

.PATH: ${SRCTOP}/sys/dev/usb/storage
KMOD=	cfumass

SRCS=	bus_if.h device_if.h opt_bus.h opt_usb.h usb_if.h usbdevs.h \
	cfumass.c

.include <bsd.kmod.mk>
