#	from: @(#)Makefile	5.5 (Berkeley) 5/11/90
# $FreeBSD: b612f2bc974bf0bd1635eaf40683df299732159d $

PROG=	rtprio
LINKS=  ${BINDIR}/rtprio ${BINDIR}/idprio
MLINKS= rtprio.1 idprio.1

WARNS?=	2

.include <bsd.prog.mk>
