# Makefile to build LCD control software for ppi(4) interface.
#
# $FreeBSD: fa409ee91e2cd4b8e395258f74ceaf0249461bbd $

PACKAGE=examples
FILESDIR=${SHAREDIR}/examples/ppi
PROG=	ppilcd
MAN=

.include <bsd.prog.mk>
