# $FreeBSD: 7fc7457741d37bd9d7d54ffc31b3de1e91bbac6c $

.PATH: ${SRCTOP}/sys/dev/rtsx

KMOD=	rtsx
SRCS=	rtsx.c
SRCS+=	device_if.h bus_if.h pci_if.h mmcbr_if.h opt_mmccam.h opt_cam.h

.include <bsd.kmod.mk>
