# $FreeBSD: 87aa812b804931c0962a7c63c22798423f50efd7 $
PREFIX?=        /usr/local
LOCALBASE?=     /usr/local
BINDIR=         ${PREFIX}/sbin
PROG=		indent_wrapper
MAN=
SRCS+=		indent_wrapper.c

.include <bsd.prog.mk>
