# $FreeBSD: 8ebd53f115c3ed6c5295687cefe75506cf8bd6f3 $

.PATH: ${SRCTOP}/sys/dev/xe

KMOD=	if_xe
SRCS=	if_xe.c if_xe_pccard.c
SRCS+=	bus_if.h card_if.h device_if.h pccarddevs.h

.include <bsd.kmod.mk>
