# $FreeBSD: 74f164204172521ea1b31818359d2027c312a5f4 $

.PATH: ${.CURDIR}/../../security/mac_veriexec
.PATH: ${.CURDIR}/../../crypto/sha2

KMOD=	mac_veriexec_sha256
SRCS=	mac_veriexec_sha256.c sha256c.c

.include <bsd.kmod.mk>

