# $FreeBSD: 88e8c21f60b4bb72fc3a7e79dce2595b56ff0003 $

.PATH: ${.CURDIR:H}/ctm_rmail

PROG=	ctm_smail
MAN=
SRCS=	ctm_smail.c error.c

CFLAGS+= -I${.CURDIR:H}/ctm_rmail

WARNS?=	2

.include <bsd.prog.mk>
