# $FreeBSD: cf1fa812d3d60fe2f58d353a05792334ffce16df $

CONFS=	devfs.conf devfs.rules
CONFSDIR_devfs.rules=	/etc/defaults
CONFSMODE_devfs.rules=	600
PACKAGE=runtime
PROG=	devfs
SRCS=	devfs.c rule.c
MAN=	devfs.8

.include <bsd.prog.mk>
