#	$OpenBSD: Makefile,v 1.1 1997/01/26 02:23:20 millert Exp $
# $FreeBSD: 7c9475b95251e933363e7c6127d0f24d81682bb9 $

PACKAGE=ufs
PROG=	fsirand
MAN=	fsirand.8
LIBADD=	ufs
WARNS?=	3

.include <bsd.prog.mk>
