#	$OpenBSD: Makefile,v 1.1 1997/01/26 02:23:20 millert Exp $
# $FreeBSD: 1fc54ff44687d8e77330644e41e1e4cb1b70134f $

PACKAGE=runtime
PROG=	fsirand
MAN=	fsirand.8
LIBADD=	ufs
WARNS?=	3

.include <bsd.prog.mk>
