# $FreeBSD: 7bda6b98c37655306f469ca4f6105f614b3e3fab $

.PATH:		${SRCTOP}/sys/dev/acpica
KMOD=		acpi_dock
SRCS=		acpi_dock.c opt_acpi.h device_if.h bus_if.h acpi_if.h
SRCS+=		opt_ddb.h

.include <bsd.kmod.mk>
