# $FreeBSD: 05532f3824d913a6c01a242ad009e89cd100f5cb $

PACKAGE=	tests

TESTSDIR=	${TESTSBASE}/usr.bin/bmake/basic/t3

TAP_TESTS_SH=	legacy_test

${PACKAGE}FILES+=		expected.status.1
${PACKAGE}FILES+=		expected.stderr.1
${PACKAGE}FILES+=		expected.stdout.1

.include <bsd.test.mk>
