#!/bin/sh
#
# $FreeBSD: af7acfbdc8ea40ac213b907a0066a7667a7cf281 $
#

# Configuration file for release/release.sh to build powerpc/powerpc64le.

TARGET="powerpc"
TARGET_ARCH="powerpc64le"
KERNEL="GENERIC64LE"
