#!/bin/sh
#
# $FreeBSD: 13b043e4cd233efcdd9b01d025ac8ae54ec9bda5 $
#

# Configuration file for release/release.sh to build powerpc/powerpcspe.

TARGET="powerpc"
TARGET_ARCH="powerpcspe"
KERNEL="MPC85XXSPE"
