#!/bin/sh
#
# $FreeBSD: 7c756d413dc38b7b05fb57f0e9cd4ddd7e7e048f $
#

# Configuration file for release/release.sh to build powerpc/powerpc64.

TARGET="powerpc"
TARGET_ARCH="powerpc64"
KERNEL="GENERIC64"
