# $FreeBSD: ddcfbdc6146ea5d24868716b7500f3f6334ec6e7 $

PACKAGE=	tests

NETBSD_ATF_TESTS_SH=	basic_test

${PACKAGE}FILES+=	d_basic.in
${PACKAGE}FILES+=	d_basic.out

.include <netbsd-tests.test.mk>

.include <bsd.test.mk>
