# $FreeBSD: 93f935bb38bdad2000845de8f2d63f094529ae99 $

.PATH:		${SRCTOP}/sys/dev/iicbus
KMOD		= isl12xx
SRCS		= isl12xx.c bus_if.h clock_if.h device_if.h iicbus_if.h ofw_bus_if.h opt_platform.h

.include <bsd.kmod.mk>
