# ex:ts=8
#
# Makefile for amd
# 	This file is under a "BSD" copyright (c) by David O'Brien 1998
#
# $FreeBSD: e7cd959782f2fe33c671fec273279852887b9b22 $

.PATH:	${SRCTOP}/contrib/amd/mk-amd-map

PROG=	mk-amd-map
MAN=	mk-amd-map.8

LIBADD=	amu

.include <bsd.prog.mk>
