#!/bin/sh
#
# $FreeBSD: 18a822012059e76faaaf83ef9357fa737970b96f $
#

# PROVIDE: adjkerntz
# REQUIRE: FILESYSTEMS
# BEFORE: netif
# KEYWORD: nojail

. /etc/rc.subr

name="adjkerntz"
start_cmd="adjkerntz -i"
stop_cmd=":"

load_rc_config $name
run_rc_command "$1"
