#!/bin/sh
#
# $FreeBSD: 52a7ac684eed006d2bb4e5080eb87546f68a0b43 $
#

# PROVIDE: archdep
# REQUIRE: mountcritremote
# KEYWORD: nojail

. /etc/rc.subr

name="archdep"
start_cmd="archdep_start"
stop_cmd=":"

archdep_start()
{
	local _arch

	_arch=`${SYSCTL_N} hw.machine_arch`
	case $_arch in
	esac
}

load_rc_config $name
run_rc_command "$1"
