#!/bin/sh
#
# $FreeBSD: 13cb5d5b69d7aac8c53ae86e6592781714654a69 $
#

# PROVIDE: auditdistd
# REQUIRE: auditd
# BEFORE:  DAEMON
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="auditdistd"
desc="Audit trail files distribution daemon"
rcvar="${name}_enable"
pidfile="/var/run/${name}.pid"
command="/usr/sbin/${name}"
required_files="/etc/security/${name}.conf"
extra_commands="reload"

load_rc_config $name
run_rc_command "$1"
