#!/bin/sh
#
# $FreeBSD: 2acbe09139ca4982f92ff2c391a9052616051bc5 $
#

# PROVIDE: autounmountd
# REQUIRE: FILESYSTEMS
# BEFORE: DAEMON
# KEYWORD: nojail

. /etc/rc.subr

name="autounmountd"
desc="daemon unmounting automounted filesystems"
rcvar="autofs_enable"
pidfile="/var/run/${name}.pid"
command="/usr/sbin/${name}"

load_rc_config $name
run_rc_command "$1"
