#!/bin/sh
#
# $FreeBSD: ecebfe0174a3d333cd325a29ba822d52e6bab246 $
#

# PROVIDE: bsnmpd
# REQUIRE: NETWORKING syslogd
# KEYWORD: nojailvnet shutdown

. /etc/rc.subr

name="bsnmpd"
desc="Simple and extensible SNMP daemon"
rcvar="bsnmpd_enable"
command="/usr/sbin/${name}"

load_rc_config $name
pidfile="${bsnmpd_pidfile:-/var/run/snmpd.pid}"
command_args="-p ${pidfile}"
run_rc_command "$1"
