#!/bin/sh
#
# $FreeBSD: d86589b84bcb2b1d1978e91ec7973db4a4c647da $
#

# PROVIDE: disks
# KEYWORD: nojail

. /etc/rc.subr

name="ccd"
desc="Concatenated disks setup"
start_cmd="ccd_start"
stop_cmd=":"

ccd_start()
{
	if [ -f /etc/ccd.conf ]; then
		echo "Configuring CCD devices."
		ccdconfig -C
	fi
}

load_rc_config $name
run_rc_command "$1"
