#!/bin/sh
#
# $FreeBSD: a656a88ac6641e9b3673652266a798a6e1c8d3d8 $
#

# PROVIDE: DAEMON
# REQUIRE: NETWORKING SERVERS

#	This is a dummy dependency, to ensure that general purpose daemons
#	are run _after_ the above are.
