#!/bin/sh
#
# $FreeBSD: c44bbe126e3ef5060468f3e9b9bd9cbb0eab0aca $
#

# PROVIDE: FILESYSTEMS
# REQUIRE: root mountcritlocal cleanvar

#	This is a dummy dependency, for services which require filesystems
#	to be mounted before starting.  It also serves as the default early /
#	late divider; after this point, rc.d directories are rescanned to
#	catch scripts from other filesystems than /.
