#!/bin/sh
#
# $FreeBSD: 996d8ada987a65aaec9b28cd635144572b7ac833 $
#

# PROVIDE: FILESYSTEMS
# REQUIRE: root mountcritlocal cleanvar tmp

#	This is a dummy dependency, for services which require filesystems
#	to be mounted before starting.  It also serves as the default early /
#	late divider; after this point, rc.d directories are rescanned to
#	catch scripts from other filesystems than /.
