#!/bin/sh
#
# $FreeBSD: 1d7e72a42ffb56c61294b4d77b0e29fa759f2d42 $
#

# PROVIDE: gssd
# REQUIRE: root
# KEYWORD: nojail shutdown

. /etc/rc.subr

name=gssd
desc="Generic Security Services Daemon"
rcvar=gssd_enable

load_rc_config $name
run_rc_command "$1"
