#!/bin/sh
#
# $FreeBSD: 2a51add38b88803b6281d4182e347f7dd7017c64 $
#

# PROVIDE: gssd
# REQUIRE: root mountcritlocal
# KEYWORD: nojail shutdown

. /etc/rc.subr

name=gssd
desc="Generic Security Services Daemon"
rcvar=gssd_enable

load_rc_config $name
run_rc_command "$1"
