#!/bin/sh
#
# $FreeBSD: 79dbf10ca57577ead19d08ab60dcc90155d0cf74 $
#

# PROVIDE: gssd
# REQUIRE: root mountcritlocal NETWORKING kdc
# BEFORE: mountcritremote
# KEYWORD: nojail shutdown

. /etc/rc.subr

name=gssd
desc="Generic Security Services Daemon"
rcvar=gssd_enable

load_rc_config $name
run_rc_command "$1"
