#!/bin/sh
#
# $FreeBSD: 70c4c70e98cc967d873e921f838986f721f0a4ea $
#

# PROVIDE: ipropd_slave
# REQUIRE: kdc
# KEYWORD: shutdown

. /etc/rc.subr

name=ipropd_slave
rcvar=${name}_enable
required_files="$ipropd_slave_keytab"
start_precmd=${name}_start_precmd

ipropd_slave_start_precmd()
{

	if [ -z "$ipropd_slave_master" ]; then
		warn "\$ipropd_slave_master is empty."
		return 1
	fi
	command_args=" \
	    $command_args \
	    --keytab=\"$ipropd_slave_keytab\" \
	    --detach \
	    $ipropd_slave_master"
}

load_rc_config $name
run_rc_command "$1"
