#!/bin/sh
#
# $FreeBSD: 3b1cb6f40d1c57fe5a8bfabb91733ce0efb45d02 $
#

# PROVIDE: iscsid
# REQUIRE: NETWORK
# BEFORE:  DAEMON
# KEYWORD: nojail

. /etc/rc.subr

name="iscsid"
desc="iSCSI initiator daemon"
rcvar="iscsid_enable"
pidfile="/var/run/${name}.pid"
command="/usr/sbin/${name}"
required_modules="iscsi"

load_rc_config $name
run_rc_command "$1"
