#!/bin/sh
#
# $FreeBSD: d2f4a291fbca08a10cd6fa669c8664ad9dd4b4d9 $
#

# Start keyserv if we are running Secure RPC

# PROVIDE: keyserv
# REQUIRE: ypset
# BEFORE: DAEMON
# KEYWORD: shutdown

. /etc/rc.subr

name="keyserv"
desc="Server for storing private encryption keys"
rcvar="keyserv_enable"
command="/usr/sbin/${name}"
start_precmd="keyserv_prestart"

keyserv_prestart()
{
	force_depend rpcbind || return 1
}

load_rc_config $name
run_rc_command "$1"
