#!/bin/sh
#
# $FreeBSD: 5a1a16c37af40e4a6a305c5acb3259b03401b73f $
#

# PROVIDE: kfd
# REQUIRE: NETWORK
# KEYWORD: shutdown

. /etc/rc.subr

name=kfd
desc="Receive forwarded tickets"
rcvar=${name}_enable
start_precmd=${name}_start_precmd

kfd_start_precmd()
{

	command_args="$command_args -i &"
}

load_rc_config $name
run_rc_command "$1"
