#!/bin/sh
#
# $FreeBSD: 2b45ba88a4b4d69c7aabb6f62f992027dad7573e $
#

# PROVIDE: LOGIN
# REQUIRE: DAEMON

#	This is a dummy dependency to ensure user services such as xdm,
#	inetd, cron and kerberos are started after everything else, in case
#	the administrator has increased the system security level and
#	wants to delay user logins until the system is (almost) fully
#	operational.
