#!/bin/sh
#
# $FreeBSD: fc8180cb22173f8e0a1b3e9c87930f4b4de1b97e $
#

# PROVIDE: lpd
# REQUIRE: DAEMON
# BEFORE:  LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name="lpd"
desc="Line printer spooler daemon"
rcvar="lpd_enable"
command="/usr/sbin/${name}"
required_files="/etc/printcap"
start_precmd="chkprintcap"

chkprintcap()
{
	if checkyesno chkprintcap_enable ; then
		/usr/sbin/chkprintcap ${chkprintcap_flags}
	fi
}

load_rc_config $name
run_rc_command "$1"
