#!/bin/sh
#
# $FreeBSD: 9cdb5577ed2b9a71dcb23233e73faf5f62edea60 $
#

# PROVIDE: NETWORKING NETWORK
# REQUIRE: netif netwait netoptions routing ppp ipfw stf
# REQUIRE: defaultroute route6d resolv bridge
# REQUIRE: static_arp static_ndp

#	This is a dummy dependency, for services which require networking
#	to be operational before starting.
