#!/bin/sh
#
# $FreeBSD: e8a3747b0fa7fb6b418ccbf625334406970a0033 $
#

# PROVIDE: nfscbd
# REQUIRE: NETWORKING nfsuserd
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="nfscbd"
desc="NFSv4 client side callback daemon"
rcvar="nfscbd_enable"
command="/usr/sbin/${name}"
sig_stop="USR1"

load_rc_config $name

run_rc_command "$1"
