#!/bin/sh
#
# $FreeBSD: 36292ae3f7b7b096c7b98c3aadb7e734799b99e5 $
#

# PROVIDE: mail
# REQUIRE: LOGIN

# XXX - TEMPORARY SCRIPT UNTIL YOU WRITE YOUR OWN REPLACEMENT.
#
. /etc/rc.subr

load_rc_config

if [ -n "${mta_start_script}" ]; then
	[ "${mta_start_script}" != "/etc/rc.sendmail" ] && \
	    sh ${mta_start_script} "$1"
fi
