#!/bin/sh
#
# $FreeBSD: ef87bcba8f83b480e8fd0e9f9d73aabcf59ef98f $
#

# PROVIDE: rarpd
# REQUIRE: DAEMON FILESYSTEMS
# BEFORE:  LOGIN
# KEYWORD: nojailvnet

. /etc/rc.subr

name="rarpd"
desc="Reverse ARP daemon"
rcvar="rarpd_enable"
command="/usr/sbin/${name}"
required_files="/etc/ethers"

load_rc_config $name
pidfile="${rarpd_pidfile:-/var/run/${name}.pid}"

run_rc_command "$1"
