#!/bin/sh
#
# $FreeBSD: 3e50a39ff66a2eaeb1ad8117f0954de749f36d88 $
#

# PROVIDE: rpcbind
# REQUIRE: NETWORKING ntpdate syslogd
# KEYWORD: shutdown

. /etc/rc.subr

name="rpcbind"
desc="Universal addresses to RPC program number mapper"
rcvar="rpcbind_enable"
command="/usr/sbin/${name}"

stop_postcmd='/bin/rm -f /var/run/rpcbind.*'

load_rc_config $name
run_rc_command "$1"
