#!/bin/sh
#
# $FreeBSD: b58d59b8c105bfe95e33c199e2b84d9d13cba822 $
#

# PROVIDE: rwho
# REQUIRE: DAEMON
# BEFORE:  LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name="rwhod"
desc="System status server"
rcvar="rwhod_enable"
command="/usr/sbin/${name}"

load_rc_config $name
run_rc_command "$1"
