#!/bin/sh
#
# $FreeBSD: 8e2be857e86f6e74a64f546dd46af44dd31ff2c6 $
#

# PROVIDE: sdpd
# REQUIRE: DAEMON
# BEFORE: LOGIN
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="sdpd"
desc="Bluetooth Service Discovery Protocol daemon "
command="/usr/sbin/${name}"
rcvar="sdpd_enable"
required_modules="ng_btsocket"

load_rc_config $name
control="${sdpd_control:-/var/run/sdp}"
group="${sdpd_groupname:-nobody}"
user="${sdpd_username:-nobody}"
command_args="-c ${control} -g ${group} -u ${user}"

run_rc_command "$1"
