#!/bin/sh
#
# $FreeBSD: 04468ef0fe647aa357d355992553e85ad3fe41e7 $
#

# PROVIDE: SERVERS
# REQUIRE: mountcritremote sysvipc linux ldconfig savecore watchdogd

#	This is a dummy dependency, for early-start servers relying on
#	some basic configuration.
