#!/bin/sh
#
# $FreeBSD: fbfae2ad9bfe02b514df1724722b425454a87159 $
#

# PROVIDE: swaplate
# REQUIRE: mountlate
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="swaplate"
desc="Setup late swap space"
start_cmd='/sbin/swapon -aLq'
stop_cmd='/sbin/swapoff -aLq'

load_rc_config swap
run_rc_command "$1"
