#!/bin/sh
#
# $FreeBSD: 6b8aa43844b572af918a2d197a64aa117ddbd46a $
#

# PROVIDE: swap
# REQUIRE: disks
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="swap"
desc="Setup swap space"
start_cmd='/sbin/swapon -aq'
stop_cmd=':'

load_rc_config $name
run_rc_command "$1"
