#!/bin/sh
#
# $FreeBSD: 0effbe7e22cad49a2dec4729ecbce951f2b1f67a $
#

# PROVIDE: sysvipc
# REQUIRE: archdep
# KEYWORD: nojail

. /etc/rc.subr

name="sysvipc"
desc="Load SysV IPC modules"
rcvar="sysvipc_enable"
start_cmd="${name}_start"
stop_cmd=":"

sysvipc_start()
{
	load_kld sysvmsg
	load_kld sysvsem
	load_kld sysvshm
}

load_rc_config $name
run_rc_command "$1"
