#!/bin/sh
#
# $FreeBSD: releng/12.2/libexec/rc/rc.d/sysvipc 364880 2020-08-27 19:35:02Z trasz $
#

# PROVIDE: sysvipc
# REQUIRE: archdep
# KEYWORD: nojail

. /etc/rc.subr

name="sysvipc"
desc="Load SysV IPC modules"
rcvar="sysvipc_enable"
start_cmd="${name}_start"
stop_cmd=":"

sysvipc_start()
{
	load_kld sysvmsg
	load_kld sysvsem
	load_kld sysvshm
}

load_rc_config $name
run_rc_command "$1"
