#!/bin/sh
#
# $FreeBSD: 7126ff854748b950b237c136fe21a235e98faea4 $
#

# PROVIDE: timed
# REQUIRE: DAEMON
# BEFORE:  LOGIN
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="timed"
desc="Time server daemon"
rcvar="timed_enable"
command="/usr/sbin/${name}"

load_rc_config $name
run_rc_command "$1"
