#!/bin/sh
#
# $FreeBSD: 8c457a98c0c5bc479e08223a556d03963a086275 $
#

# PROVIDE: utx
# REQUIRE: DAEMON FILESYSTEMS
# BEFORE: LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name="utx"
desc="Manage the user accounting database"
start_cmd="utx boot"
stop_cmd="utx shutdown"

load_rc_config $name
run_rc_command "$1"
