#!/bin/sh
#
# $FreeBSD: edf259bac57e82de8b85663849e9d00415b7e1b0 $
#

# PROVIDE: zfsd
# REQUIRE: devd zfs
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="zfsd"
rcvar="zfsd_enable"
command="/usr/sbin/${name}"

load_rc_config $name
run_rc_command "$1"
