#!/bin/sh
#
# $FreeBSD: f98693f2cb13fc9afa9df99d17b74baba519d43f $
#

# PROVIDE: zpool
# REQUIRE: hostid disks
# BEFORE: mountcritlocal
# KEYWORD: nojail

. /etc/rc.subr

name="zpool"
desc="Import ZPOOLs"
rcvar="zfs_enable"
start_cmd="zpool_start"
required_modules="zfs"

zpool_start()
{
	local cachefile

	for cachefile in /etc/zfs/zpool.cache /boot/zfs/zpool.cache; do
		if [ -r $cachefile ]; then
			zpool import -c $cachefile -a -N && break
		fi
	done
}

load_rc_config $name
run_rc_command "$1"
