#
# $FreeBSD: 16b42414371fc8e01d5660265b5475a539f71a07 $
#
SRCS=	envctl.c
PROG=	envctl

CFLAGS+=-Wall -I../../../include

CLEANFILES=	${PROG}.core

MAN=

.include <bsd.prog.mk>

test: ${PROG}
	@env -i sh envtest.t
