#
# $FreeBSD: adc2a987d5345f596e22e1483f00dd0b8eec9d6b $
#
SRCS=	timings.c
PROG=	timings

CFLAGS+=-Wall -I../../../include

CLEANFILES=	${PROG}.core

MAN=

.include <bsd.prog.mk>

test: ${PROG}
	@./timings
