#	$FreeBSD: 075119abd542e28626665ae8c4ab62988e9f1da3 $

SUBDIR=		libipf .WAIT
SUBDIR+=	ipf ipfs ipfstat ipmon ipnat ippool
# XXX Temporarily disconnected.
# SUBDIR+=	ipftest ipresend ipsend
SUBDIR_PARALLEL=

.include <bsd.subdir.mk>
