#	$FreeBSD: 6126564e9821283813f4465c9575353624ac8d3b $

SUBDIR=		libipf .WAIT
SUBDIR+=	ipf ipfs ipfstat ipmon ipnat ippool
# XXX Temporarily disconnected.
# SUBDIR+=	ipftest ipresend
SUBDIR_PARALLEL=

.include <bsd.subdir.mk>
