# $FreeBSD: releng/12.2/tests/sys/fifo/Makefile 360898 2020-05-11 15:21:03Z markj $

TESTSDIR=	${TESTSBASE}/sys/fifo

PLAIN_TESTS_C+=	fifo_create
PLAIN_TESTS_C+=	fifo_io
ATF_TESTS_C+=	fifo_kqueue
PLAIN_TESTS_C+=	fifo_misc
PLAIN_TESTS_C+=	fifo_open

TEST_METADATA.fifo_create+=	required_user="root"
TEST_METADATA.fifo_open+=	required_user="root"

.include <bsd.test.mk>
