# $FreeBSD: ede51a9c6c4255be12d443624862ba7bb8681f3b $

.include <bsd.own.mk>

PACKAGE=	tests

ATF_TESTS_SH=	zdiff_test
NETBSD_ATF_TESTS_SH=	gzip_test

${PACKAGE}FILES+=	foo.diff

.include <netbsd-tests.test.mk>

.include <bsd.test.mk>
