# $FreeBSD: 0d77b3f4a2cb47c24299305bc1c9d712a34dd753 $

.PATH: ${SRCTOP}/sys/dev/ata/chipsets

KMOD=	atamarvell
SRCS=	ata-marvell.c
SRCS+=	ata_if.h bus_if.h device_if.h pci_if.h

.include <bsd.kmod.mk>
