# $FreeBSD: b5e78f223b899ce2f52c81aa55ee360a8fc0d01a $

.PATH:		${SRCTOP}/sys/dev/smbus
KMOD		= smbus
SRCS		= device_if.h bus_if.h smbus_if.h smbus_if.c \
		  smbconf.h smbconf.c smbus.h smbus.c

.include <bsd.kmod.mk>
