#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: releng/11.3/usr.bin/rs/Makefile 327186 2017-12-26 03:59:49Z asomers $

.include <src.opts.mk>

PROG=	rs

HAS_TESTS=
SUBDIR.${MK_TESTS}+= tests

.include <bsd.prog.mk>
