# $FreeBSD: ddf1323725dae8c9a7b1d30708e001422816ef16 $

SUBDIR=	beyond4.3 \
	bufbio \
	contents \
	devfs \
	diskperf \
	fsinterface \
	jail \
	kernmalloc \
	kerntune \
	malloc \
	newvm \
	relengr \
	sysperf \
	timecounter

SUBDIR_PARALLEL=

.include <bsd.subdir.mk>
