# $FreeBSD: releng/12.2/usr.bin/clang/llvm-lto2/Makefile 356462 2020-01-07 19:49:10Z dim $

PROG_CXX=	llvm-lto2
MAN=

SRCDIR=		llvm/tools/llvm-lto2
SRCS=		llvm-lto2.cpp

LIBADD+=	z

.include "../llvm.prog.mk"
