#	@(#)Makefile	5.33.1.1 (Berkeley) 5/6/91
# $FreeBSD: 7ecf7c8965a344da7d9d73c9ac2fd2c63453aed9 $

.include <src.opts.mk>

SUBDIR= lib .WAIT \
	usr.bin

SUBDIR.${MK_TESTS}+= tests

SUBDIR_PARALLEL=

.include <bsd.subdir.mk>
