# $FreeBSD: 2b58e37dad9cf51bdcf0bf5a3d528429b0e0d4d1 $

.PATH: ${SRCTOP}/sys/dev/ata

KMOD=	atacard
SRCS=	ata-card.c
SRCS+=	ata_if.h bus_if.h card_if.h device_if.h pccarddevs.h

.include <bsd.kmod.mk>
