#	@(#)Makefile	8.1 (Berkeley) 6/9/93
# $FreeBSD: 8baf6936d7bc386555fa2153db2340a6cb600aa6 $

.include <src.opts.mk>

PROG=	renice
MAN=	renice.8

HAS_TESTS=
SUBDIR.${MK_TESTS}+= tests

.include <bsd.prog.mk>
