# $FreeBSD: 30e373b9b533f87af59fd52a07606140f7592df0 $

.PATH:		${SRCTOP}/sys/dev/acpi_support

KMOD=		acpi_rapidstart
SRCS=		acpi_rapidstart.c opt_acpi.h device_if.h bus_if.h acpi_if.h

.include <bsd.kmod.mk>
